### ISSUE TITLE
Dark mode doesn't apply to the menu bar in Ubuntu

### ISSUE THREAD

**Issue by justinkterry** [Automattic/simplenote-electron#1036]
In Ubuntu 18.04 and 18.10 (the main versions you should be trying to support), using the current version of simplenote, the menu bar stays white. After poking around for awhile, this is because the menu bars color is taken from the system theme, and so goes with whatever color that is. The default themes in 1.804 and 18.10 both cause it to be the same white as the non-dark theme.

Edit: This seems like it shouldn't even be an inconvenience, because it's my understanding that you already have to recreate the menus in full JS to port the electron app to your webapp. It would also let you make the menus font, style and size match the rest of the app (which they don't).

**Comment by mirka** [comment]
Thanks for looking into this!

> you already have to recreate the menus in full JS to port the electron app to your webapp

In fact no, we're not going to be recreating the menus for the webapp. For menu items that aren't already part of the settings dialog or the browser's menu, we'll be adding to the settings dialog or elsewhere in the UI.

> the menu bars color is taken from the system theme

Given this limitation, is there anything you recommend we do about this?

**Comment by mirka** [comment]
If anything, we're leaning towards making the menu hideable. This Dark Mode problem is another reason we should consider it, along with enlarging the workspace (#1048). The idea is to have all (or almost all) app features available in the main app UI, without relying on the menu bar.

I'm going to close this in favor of #293, since there is nothing we can do about the menu bar color.
