### ISSUE TITLE
Add support for images

### ISSUE THREAD

**Issue by Bread7** [Automattic/simplenote-electron#1069]
#### Screenshot / Video
-->

Hi, sorry for my poor formatting or wording as I am relatively new to Github and its operations. I have a feature request I want for Simplenote. 
Whenever I add a photo/image into Simplenote, the image will have to be in my local computer because the path of the image is set to a directory in my local computer and when viewing on any other platforms, the image will not be displayed. 
Hence, I have a suggestion to make which is possibly to have a database where we can upload our images and use that database to set our path to image. This way when we view our notes from different platforms, we are able to see the picture.
Sorry if this is a duplicated issue if there is and thank you for making this beautiful application.
Thanks!

**Comment by mirka** [comment]
Thanks for posting the request! This is a highly requested feature, and while we have no immediate timeline, it is something we are considering.

Related: #570

**Comment by Bread7** [comment]
Alright, that is nice to hear from you. Thank you!

**Comment by weyderfs** [comment]
News about this?

**Comment by sebastiankayser** [comment]
I am currently using Google Tasks to keep track of things. Because they don't support images I was looking for an alternative and came across Simple Note. A news item said that it would support images.

The current approach however seems to be very clunky. I tried embedding an image URL via the 

![alt](https://example.com/path/to/image)

syntax, but this didn't work.

For now, I have found a related thread over at reddit.com where they suggest some alternatives.

https://www.reddit.com/r/productivity/comments/6cibcb/looking_for_a_simple_note_keeping_software_with/

People looking for a simple approach to embedding images might want to look there.

**Comment by sebastiankayser** [comment]
To spare others the search for a task keeping software with image support. There are many simple task management tools and I agree with the developers that adding image support might lead them astray.

An excellent, free, feature-rich, and easy to use solution with image support is Microsoft OneNote. They have a web frontend and mobile apps.

https://www.onenote.com/

It takes maybe 15 minutes to get used to their interface, but then it's a breeze. I can only recommend it!

**Comment by bkielbasa** [comment]
I'd love to see this feature. I very often copy&paste images into my notes and lack of this functionality makes simplenote not usable for me, too.

**Comment by jfaughnan** [comment]
I respect how challenging this would be to do well. I still use nvAlt for example and love having my notes in a spotlight indexed plaintext file on my Mac.

There are times though ... I would love to see image support if it could be done using something like markdown with images stored separately from plaintext so that plaintext compatibility were maintained. (Hint: App requirement). Of course that makes it easier to break image embedding, but I'd take those odds.

**Comment by ChrissiePollock** [comment]
Another request for this in #2259880-zen

**Comment by theck13** [comment]
Using insecure images in notes causes some browsers to show messages about an insecure connection.  See the screenshot from Firefox below for illustration.

<img width="620" alt="insecure" src="https://user-images.githubusercontent.com/3827611/63043092-b8fe1600-be88-11e9-8078-20aa14e217f7.png">

Looking at the developer console, the insecure images are listed.  In the example above, replacing the http://i.imgur.com/EDDSxZK.jpg URL with https://camo.githubusercontent.com/1e30fd9d766d8b6374a9d004a44bb74cb7e04ace/687474703a2f2f692e696d6775722e636f6d2f5075667a6759582e6a7067 resolved the connection message.

**Comment by alokprasad** [comment]
any update on this ?

**Comment by belcherj** [comment]
No update as of now.

**Comment by opdavies** [comment]
This is unfortunate. I'd switched from Bear on macOS to Simplenote as I use a mixture of macOS and Linux now, and a lack of support for images is a big blocker for me.

**Comment by Richard-Lance** [comment]
It is a pain, I moved back to Simplenote from Mac Notes so that I have a cross-platform product to include Ubuntu. My work-around is to add the Dropbox link for an image to Simplenote. So clicking on the note, takes me to the image.

**Comment by jpxsat** [comment]
Hi. Just wanted to say "thank you", this is a very good and simple program for notes, cross-platform which is absolutely great.
I add to this request, but I do feel that in any case it should not be a show-stopper for using  _**Simple**_note; when this feature arrives, it will be more than welcome for us  _**simple**_users 👍 Keep up the good work!

**Comment by alokprasad** [comment]
I guess Top features are:

1. Pasting Images
2. Code Pasting
3. Easy PDF export
4.two location for saving contents(if one deleted other can be used)

**Comment by cpelley** [comment]
Assuming that publishing the image elsewhere isn't an option/desirable (google drive, github via ghpages, gitlab pages etc.), one ~workaround is to encode your images to base64 and include them in your notes that way.

imagemagick (linux) will do this encoding for you or otherwise there are plenty of online converters available (example: https://base64.guru/converter/encode/image)

```
<img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZA..."/>
```

This has the drawback that adding a pretty long URI gets in a way of your notes... also this doesn't work in the simplenote client (android).

**Comment by NightMachinery** [comment]
Pasting images and being able to resize with the mouse is critical to a screenshot note-taking approach.

**Comment by nathancchu** [comment]
any updates on this?

**Comment by tomaskristoffeldm** [comment]
any update here?

**Comment by codebykat** [comment]
Hi folks, any updates would be posted here, as well as on the [Simplenote blog](https://simplenote.com/blog/). As we've said, it's an oft-requested feature, but not on our immediate roadmap. There are both technical and non-technical complexities (read: content moderation) to allowing image uploads to our servers.

As a workaround, you may upload an image to any other service that provides a public link, and embed it within a note using Markdown syntax.

**Comment by antaki93** [comment]
To add an image to a Simplenote note, you need:
1. Add to your note a line like `![](https://example.com/your/image/address)`.
2. In the Actions menu select Markdown checkbox.
3. Click the Preview button to see result.

(I use IPFS to store images. You can install [desktop client](https://github.com/ipfs/ipfs-desktop) and add any files to the distributed storage. All your links will look like `https://ipfs.io/ipfs/hash-of-your-image-file`).

**Comment by OracleJMT22** [comment]
Get your butts together, or I will just fork Simplenote with another branding and name, with the feature build in, or make others do it. Can't be that hard, guys, c'mon.

**Comment by bagustris** [comment]
To use internal image (instead of an image from the internet), you could use the following format,  

    ![Alt text](file:///your-image-absolute-path)

Example: 

    ![]file:///home/bta/Dropbox/simplenote-images/consistency.jpeg


Notice the `file:///xxx` format instead of the original image path (the format in which a browser opened the image). This only works locally  (no image in Android version).

@
I suggest this feature exists on the future paid version of Simplenote.

**Comment by aemxn** [comment]
Bump. Need this feature. Make use of Markdown feature of formatting images, SimpleNote just have to display it, not storing anything.
