### ISSUE TITLE
Simplenote Linux no longer running after 1.3.2

### ISSUE THREAD

**Issue by ekohilas** [Automattic/simplenote-electron#1076]
I get this output when running simplenote after 1.3.2
`simplenote: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory`

Additionally, when following the update link, I was no longer given the direct download, and I am now no longer sure which binary I should be running.

OS version: `Linux mint 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by mirka** [comment]
That seems to be an error that occurs when the 32/64-bit architecture is mismatched.

Since you seem to be on a 64-bit machine, can you verify that you are using a 64-bit version of Simplenote? From the [latest packages here](https://github.com/Automattic/simplenote-electron/releases/latest), the `-amd64.deb` one is probably for you. (If not, try `-x86_64.rpm`)

> I was no longer given the direct download, and I am now no longer sure which binary I should be running.

We moved away from direct downloads for Linux users, since they are on all sorts of systems and therefore want different packages. There is no way to reliably detect which package the user needs, so we are asking them to pick their own. The `-amd64.deb` package should work for most users.

**Comment by ekohilas** [comment]
Working now, thank you!
It seems I downloaded the wrong package then.
Perhaps the solution to this is to link the direct download to be relative to the binary that was initially downloaded?

**Comment by mirka** [comment]
> Perhaps the solution to this is to link the direct download to be relative to the binary that was initially downloaded?

Yes, it would be nice if we could do that!
