### ISSUE TITLE
Bold Markdown not previewing correctly on Linux

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/simplenote-electron#1137]
#### Steps to reproduce
1. Use the `**bold**` or `***bold and italic***` Markdown code in a note
2. Preview the note

#### What I expected
Text should be bold or bold and italic

#### What happened instead
Text is regular weight, or regular weight and italicized

#### Simplenote version
1.3.4

#### OS version
Linux Mint 19.1

#### Screenshot / Video
![Simplenote Editor](https://cld.wthms.co/9rhYFr+)
![Simplenote Preview](https://cld.wthms.co/2jfURH+)

Reported in #1691591-zen

**Comment by mirka** [comment]
This is likely caused by a suitable bold font not being available on the user's machine.

If they visit this page on their machine in Google Chrome, we can check to see if there's anything we can do about it on our end: https://codepen.io/_mirka_/pen/BvVPbY

We want to know whether "Test A" and/or "Test B" is rendering the bold parts.

**Comment by edequalsawesome** [comment]
@mirka Hey! I asked the user to try that test, and Test B is rendering the bold text -- Test A is not. The user supplied a screenshot:

![User Screenshot](http://cld.wthms.co/C3CaWe+)

Let me know if there's anything we can do to help the user, or if there's any other information you need 😃

**Comment by mirka** [comment]
My guess is that they have the Segoe font installed on their machine, but don’t have the Semibold weight. So they could either install the Semibold, or disable the Segoe font altogether. (If they disable Segoe, it should fall back to another font.)
