### ISSUE TITLE
Keyboard shortcuts are not documented

### ISSUE THREAD

**Issue by Pand9** [Automattic/simplenote-electron#1167]
Keyboard shortcuts are not documented at all, for the Linux (Electron?) app and the web app.

I would like them to be visible somewhere in the app.

"Preview markdown", which is useful during writing a note, would be the most important for me. I have found out here: https://github.com/Automattic/simplenote-electron/issues/37 that this function exists, but that shortcut doesn't work.

I have found a list of working shortcuts there: https://github.com/Automattic/simplenote-electron/issues/700 but "preview markdown" is missing.

**Comment by mirka** [comment]
@Pand9 Thanks for the report!

Toggle Markdown Preview should be working as `Ctrl+Shift+P` (or `Cmd+Shift+P` in Mac Electron). If this is not working for you, can you check that Markdown is enabled for your note, and that the Preview button works when you click it?

<img width="675" alt="button placement" src="https://user-images.githubusercontent.com/555336/51475571-197f1600-1dc6-11e9-8b81-f21fb8a0bd11.png">

**Comment by SonGokussj4** [comment]
Hi, just tried downloading v1.4.0-beta for Linux and found that CTRL+SHIFT+P does what I wanted from Simplenote for ages :-) So that's nice. But it's true it's nowhere to be documented. I just "tried" the CTRL+SHIFT+P. (because I found that there exists ctrl+shift+f shortcut)

Could be within "Preview button" annotation upon mouse-over.

**Comment by mirka** [comment]
@SonGokussj4 I agree, I was thinking of adding mouse-over hints too. I'm going to add that to the todo list, and close this in favor of #700.
