### ISSUE TITLE
Windows installation without admin privileges

### ISSUE THREAD

**Issue by devisions** [Automattic/simplenote-electron#1181]
Hello!

Can this be installed without admin privileges? I would love to try it.
Technically, that is possible, I am questioning this more from a planning perspective.

Thanks

#### Simplenote version
1.4.0

#### OS version

Windows 7 Enterprise

**Comment by roundhill** [comment]
Not sure, have you tried installing it?

**Comment by vision8tech** [comment]
Yes, of course. Tried and it asks for some credentials with admin rights.

Running `Simplenote-win-1.4.0.exe` it firsts pops up a dialog window, saying that "You are about to run this Executable with admin rights". Unfortunately, on that workstation I don't have admin rights.

**Comment by vision8tech** [comment]
Clicking `Cancel` it ends the installation. I assume it all relates to the fact that some file associations are involved and for such cases admin privileges are needed. An installation example that works well is Boostnote, maybe that can help.

Thanks.

**Comment by vision8tech** [comment]
An example of such issue and the solution: https://github.com/electron-userland/electron-builder/issues/772

**Comment by PhiLhoSoft** [comment]
That's why I hate these apps available only with installers (no zip version we can unzip where we want), not asking for installation path, forcing an icon on the desktop and other places, perhaps forcing file associations. It is simpler for the average user, but infuriating for those wanting control over where / how apps install.
I appreciate the installers where, by default, you have the simple install behavior, but offering an option for finer settings.

**Comment by thomasstache** [comment]
So is this just about changing that one line to `perMachine = false`?
https://www.electron.build/configuration/nsis

Or are there more things needed, like tests or similar?
