### ISSUE TITLE
Add 2-factor authentication with oauth

### ISSUE THREAD

**Issue by cpasternack** [Automattic/simplenote-electron#1269]
I am using simplenote across multiple devices: linux desktop, command line server, android application, and web. Is it within the project scope to add the ability to use an oauth one time pass token to authenticate, in addition to a username and password?

Having the ability to use not just a username and password, but an oauth token to authenticate would greatly put my mind at ease when I have to use a public computer.  I have this enabled on almost every single application that crosses platforms, and it is becoming common practise.

**Comment by lizkarkoski** [comment]
Another request for 2fa that came to us from Twitter: 
https://twitter.com/maxbuijsman/status/1173587122214846464

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by lizkarkoski** [comment]
Another request for Simplenote 2 FA that came from Twitter:
https://twitter.com/ammarmalik1/status/1191098915581505537

**Comment by supernovia** [comment]
(adding new notes to simplenoteideas)

**Comment by cmosetick** [comment]
I see 2 closed items related to `2FA` / `MFA` in this projects issue tracker...
However, I still do not see any options for 2FA or MFA on simplenote.com or in the Electron App.
Trying to understand why these are closed items.

I see no options for hardware token support for the Electron App.
Nor the less optimal, but popular "Authenticator App" option.

I **do not see** MFA options on `staging.simplenote.com` or `app.simplenote.com`

FYI - I do see FaceID or Passcode as options in the iOS App. (But no token support)

**Comment by dmsnell** [comment]
> Trying to understand why these are closed items.

Hi @cmosetick 👋 thanks for approaching with an inquisitive mind. We’ve closed these issues because we don’t have any imminent plans to add the feature and because we track feature requests with a tool that isn’t published here.

We set our priorities by balancing our own vision for the product, the things customers like you want and share, and the technical complexity required to make it happen. This particular feature isn’t something at the top of that list.

We would like to add it and hopefully we will be able to eventually. Right now though we have been occupied with other work, also important to people.

If you find a closed issue or especially if you find more than one closed issue for the same request that’s a good indicator that it’s unlikely we’ll be adding or addressing the request any time soon. Feel free to share if you have additional thoughts not already conveyed in the discussion. We do try to prioritize contributions and help out if you want to try and add a feature yourself.

When and if we add the 2FA/MFA we’ll announce it. You can keep abreast of big updates on simplenote.com

**Comment by jabronimus** [comment]
Truly a terrible response.

Time to start looking for alternatives.


> Hi @cmosetick 👋 thanks for approaching with an inquisitive mind. We’ve closed these issues because we don’t have any imminent plans to add the feature and because we track feature requests with a tool that isn’t published here.
> 
> We set our priorities by balancing our own vision for the product, the things customers like you want and share, and the technical complexity required to make it happen. This particular feature isn’t something at the top of that list.
> 
> We would like to add it and hopefully we will be able to eventually. Right now though we have been occupied with other work, also important to people.
> 
> If you find a closed issue or especially if you find more than one closed issue for the same request that’s a good indicator that it’s unlikely we’ll be adding or addressing the request any time soon. Feel free to share if you have additional thoughts not already conveyed in the discussion. We do try to prioritize contributions and help out if you want to try and add a feature yourself.
> 
> When and if we add the 2FA/MFA we’ll announce it. You can keep abreast of big updates on simplenote.com

**Comment by JannemanDev** [comment]
2FA should be top priority. People use SimpleNote for all sorts of stuff which include privacy sensitive stuff. Just my 2 cents but I think its way way overdue and a wrong decision that was made back in 2019 by not including it in your roadmap.

**Comment by dnet890** [comment]
even lengthy and complex password is not enough to prevent data breach. that is why 2fa is quite important nowadays.

**Comment by krampepampe** [comment]
I fully agree. Missing 2FA is a no-go for me. Goodbye!
