### ISSUE TITLE
Add all available keyboard shortcuts to tooltips

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#1442]
### What 

We should add hints for keyboard shortcuts to all the buttons that have them, like the Markdown Preview hint:

![image](https://user-images.githubusercontent.com/8658164/60899947-4a171700-a263-11e9-87b1-9d6fa8abfa04.png)

### Why
In https://github.com/Automattic/simplenote-electron/pull/1214 we added custom tooltips with the option to add hints for keyboard shortcuts. That PR added a hint for the Markdown Preview shortcut, which was near impossible to discover previously. For consistency, we should add them wherever a shortcut is available.

As @SylvesterWilmott noted:

> the tips can easily become the place a user looks for shortcut hints, so we should aim to be consistent.

h/t @msilbers for the suggestion (internal ref: p5T066-Uu-p2)

**Comment by b3u** [comment]
is there a list of shortcuts to accompany this?

**Comment by rachelmcr** [comment]
Thanks for jumping in on this issue, @b3u! :)

There isn't a comprehensive list of shortcuts as far as I know, and I haven't done a full audit to confirm what's needed, so that's part of this task. The shortcuts I'm aware of that could be added as tooltips are these:

- New Note
- Toggle Sidebar
- Menu (to open the tags list)

You can also check the app menu for shortcuts or look through the code (e.g. for `handleShortcut`) for additional shortcuts, to see if you find any others that could be added as tooltips to icons.

**Comment by b3u** [comment]
List of current shortcuts: http://simp.ly/p/rsnDV7

**Comment by b3u** [comment]
I changed the titles for the icons in `/lib/node-editor/index.jsx`, but when I tried to run it I got the following error: https://gist.github.com/b3u/2d95388f0c8b66e91746ada6fddd67c6

**Comment by rachelmcr** [comment]
@belcherj Could you help out with the error (and any other tips) here?

**Comment by belcherj** [comment]
@b3u Happy to take a look, could you push a PR? Try a rebase or merge from develop.  There is a Prettier fix required.  Not sure what caused the other error.

**Comment by Fraasi** [comment]
I was curious about the shortcuts and found my way here, so I took a peek under the hood.
So here's a list of what I found...

* cmdOrCtrl && 't'  -> toggle taglist (menu)
* cmdOrCtrl && shiftKey && 'p'  -> toggle markdown preview
* cmdOrCtrl && shiftKey && 'n' -> show notelist (only if on a smallscreen, otherwise it's always visible)
* cmdOrCtrl && shiftKey && 'ArrowUp' or 'k' -> previous note
* cmdOrCtrl && shiftKey && 'ArrowDown' or 'j' -> next note
				
theres also eventlistener for esc (keyCode 27) which cancels/clears the current search in notelist.
				
I couldn't find any shortcut for toggling the sidebar, although I think there should be one and it's rightful place in the codebase is propably [here](https://github.com/Automattic/simplenote-electron/blob/0db494a75c569fc4c4f61c7206b16c9b902dc324/lib/note-editor/index.tsx#L65).

All the other shortcuts are in the app menu and easily found there.
	
Some thoughts:
	
* Opening the markdown preview, the app should save the cursor position and when closing preview, it should focus the note and remember the cursor position.
* When using ctrl+shift+n to open the notelist, you should be able to go back to the note you were just viewing	by using the shortcut again. In short, it should toggle, not just show the notelist.
* Using menu button to open the taglist is a bit of a misnomer.
	
You can add the menu (taglist) and new note shortcuts to the tooltips easily [right here](https://github.com/Automattic/simplenote-electron/blob/0db494a75c569fc4c4f61c7206b16c9b902dc324/lib/search-bar/index.tsx#L47).

**Comment by belcherj** [comment]
We are adding an explainer dialog for keyboard shortcuts here:  https://github.com/Automattic/simplenote-electron/pull/1983

I can add shortcuts to tooltips with shortcuts but not sure when I will be able to get to it.

**Comment by dmsnell** [comment]
Resolved in #1983
