### ISSUE TITLE
Customized install & Math line in markdown & simultaneous preview

### ISSUE THREAD

**Issue by Williams-Ren** [Automattic/simplenote-electron#1453]
# Customized install

Because I didn't leave much space on C drive, I would like to install it on the other drive. And I also like to put all app in the same folder, so it will be very nice of you if you could add this feature as many other apps do.

# Math line in Markdown

I'm a calculus student which means I need to take lots of notes about math including many characters in math such as integral, superscript, subscript, and so on. However, it seems that this feature is not added into this app which made my notes unreadable since I typed them in LaTeX form. For this reason, I think it will be very crucial for this app to add on such a feature.

# Simultaneous preview

This will be a suggestion that is not very important but may improve the users' experience of new users of Markdown since many of them may type it wrongly. There are several apps which have this feature such as typora and the bear. So, I suppose it will be a good idea to add such a feature to help new users of Markdown.

PS: I suppose MD is a very powerful writing style which can save lots of time for users, so I hope this app could spend more time in improving and adding new MD grammar such as highlight, code blocks, gutt graphs, tables, and flow chart

**Comment by cecoates** [comment]
If simultaneous preview and live preview are the same, I'd dig that too.

Especially because screen space is precious and having to toggle over can be awkward.

With a live preview, could possibly do away with the preview option entirely.

Stackedit live preview:

![Screenshot 2019-08-08 at 15 47 59](https://user-images.githubusercontent.com/10121835/62737147-bae15880-b9f4-11e9-9ee1-f21afc1bea8f.png)

Ghostwriter live preview:

![Screenshot 2019-08-08 at 15 48 55](https://user-images.githubusercontent.com/10121835/62737161-c3399380-b9f4-11e9-835c-cfe428e37879.png)

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests! Since there were three requests I added this issue to all three features.
