### ISSUE TITLE
Simplenote Link sharing is not working in simplenote-electron version 1.10.0

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1696]
### Expected
- After clicking **Share** when I go to **Publish** tab, It's not giving me the sharing link. The **PUBLIC LINK** box is always empty.

### Screenshot
***![rsz_1screenshot_from_2019-11-06_13-14-47](https://user-images.githubusercontent.com/44976018/68277042-86834400-0098-11ea-97a0-1b749fca5567.jpg)***

**Comment by dmsnell** [comment]
@Donboscow the publish link can take longer than expected from time to time. it may be the case that it takes more than ten seconds to get the publish link.

If your note persists in not getting the publish link please contact our support at https://simplenote.com/contact-us/ and we can help there.

I'm closing this issue because the the publish link is working generally. It may be that there is something particular with your note that is failing to get the publish link and if that's the case we can figure it out in our support channels. Please give it at least a minute to get that publish link though without clicking again to unpublish; it may just be playing catch-up and things might work without any additional input or changes.
