### ISSUE TITLE
Normal app functions break in Windows (OS) with update window open.

### ISSUE THREAD

**Issue by rfaile313** [Automattic/simplenote-electron#1731]
### Expected

With the "Check for Updates" window open in the app, you should be able to navigate options in the app or exit the app. 

![screenshot](https://cld.wthms.co/mC4975+)

I've tested this with all other prompts in the app and it works as expected, it seems this is only broken with the Menu > Help > Check for Updates window. 

### Reproduced
***(Required)*** If you cannot reproduce this bug consistently, please elaborate.  List the steps to reproduce the behavior.  For example:
> 1. Open Simplenote
> 2. Click on Help
> 3. Click on Check For Updates
> 4. Try to Exit the app by clicking the X in the Main Window or Using the Menu items. 

Make|Model|OS Version|App Version
Operating System: Windows 10
Version: 1903
OS Build: 18362.418
App Version: Current Release and 1.11.0-beta1

User report 2500595-zen

**Comment by belcherj** [comment]
This is expected. The other modals are built into the app as html/js where this is an Electron window.  What is the use case for having access to menus or the close? If there is a valid use case for making this change I will add it to our feature requests.

**Comment by JesperTreetop** [comment]
I'm the customer who reported this and I reported it because I noticed it in a very weird way. When I clicked the menu, the *shadow* was visible but the menu wasn't, which looks completely broken and is the way Windows sometimes used to behave when it was running very low on resources. Having something be modal is fair, but clicking anything should result in a "system beep" and a rejected click. Here, it makes the entire app look broken. I wouldn't be surprised if this was an Electron issue.
