### ISSUE TITLE
Add 2FA for improved account security

### ISSUE THREAD

**Issue by vekuda** [Automattic/simplenote-electron#1766]
Note-taking apps contain private information for inherent and obvious reasons, and as I reckon that I would never store extremely private / sensitive text on Simplenote, I still care about my Simplenote account being significantly difficult to hack.

Could you please add 2-Factor Authentication in order to provide a basic safety layer to your service? I could never trust Simplenote with storing my notes on its cloud if my account is protected by a password alone.

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!

**Comment by JannemanDev** [comment]
I personally think this feature is way way overdue. 2FA is a must have feature nowadays. SimpleNote is being used by people who use it for all sorts of personal and privacy sensitive stuff. 2FA isnt even hard to implement.

**Comment by ChrissiePollock** [comment]
Requested again in #4764616-zen

**Comment by ronfischler** [comment]
I was thinking about this myself, came here and found the issue already open. I agree with JanOonk, that 2FA is a must-have feature/option for any cloud service now.

**Comment by codebykat** [comment]
Closing as we have this tracked elsewhere. It's still something we hope to implement down the road but we can't provide a timeline unfortunately -- I can say that it's not on the immediate horizon. We get plenty of requests for it, and the development team does agree on its importance; it's rather an issue of bandwidth and the amount of work required, especially since it will require cross-platform coordination. Keep an eye on the [official blog](https://simplenote.com/blog/) for any updates.

In general we use the GitHub for bug tracking and planning out our immediate roadmap; so please don't lose heart if you see that a feature request was closed. Since we have several different repositories, we consolidate feature requests internally so we can get a holistic view of what is being asked for most often. (And yes, this is high on the list.)

As far as security goes, we've hardened a few things since this issue was originally opened, including requiring email verification for any account changes and requiring a reset of insecure passwords. We do take the privacy of notes very seriously, AND we recommend against using Simplenote for super sensitive data such as passwords -- there are far better password managers out there which are tailored to the purpose, and will always be more secure than a general tool like a note-taking app (any note-taking app). The security-conscious might also be interested to know that Simplenote's note data also resides entirely on our own servers, it's not getting sent out to Google or Amazon cloud services.

Hope this background information is helpful! As I said, we hope to get to this someday.

**Comment by metabreakr** [comment]
Another request: https://twitter.com/slirx/status/1509922016618590209
