### ISSUE TITLE
Edits out of order in history of shared note

### ISSUE THREAD

**Issue by tmchartrand** [Automattic/simplenote-electron#1816]
### Expected
Even on a shared note, edits from multiple users and clients should appear in order in the note history, and the Latest version shown by default should actually be the latest edit.

### Observed
In both older version (electron app, maybe 1.4?) and web app, current version somehow reverted to older edit. On web version, that edit appears as the most recent in the history, out of order by date, followed by an edit with a more recent timestamp that appears identical to the old edit. In electron app, the old edit appears in the proper place in history, and the latest version shown is the identical new edit, with the true current version lost in between.

### Reproduced
Not sure exactly how it got in this state and haven't yet managed to reproduce a simpler example.
> 1. Note owner creates note (electron app, maybe 1.4?), Nov 30
> 2. Collaborator makes large-scale edits (iphone app), Dec 28
> 3. (speculated) note opened in electron app, change consisting of no actual edits to Nov 30 version is somehow pushed before note is synced?
> 3. Both see note reverted to initial version, with odd note history.

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

**Comment by dmsnell** [comment]
thanks for reporting @tmchartrand.

it sounds like something is fishy, but I want to make sure we separate quirks in the way syncing works from defects in the app.

the order of the edits in the revision slider _should_ come in the order that the edits applied to the account. that is, you may find that even though you made edits on device A in the real world an hour before making other edits on device B, if device B was connected to the internet and send its changes before re-connecting device A to the internet, then the edits will look like they were swapped.

we still have a ways to go to better communicate what's happening, but the revision slider is showing the order in which the edits applied to the note and that may not match when they were physically entered.

---

that being said, I'm struggling to understand the sequence of events and outcomes as described. if it's truly the Electron app version 1.4 though I wouldn't be surprised if there's out-of-order listing - we _did_ have a bug that was related to this very thing because we sorted the revisions by their listed date _instead of_ the edit sequence.

it's all very confusing, but see if what I wrote about the ordering makes sense and then would you be willing to try and expand on what you saw? if you want to share screenshots then please contact our support where we can work through this individually and privately with you.

**Comment by tmchartrand** [comment]
ok, that makes more sense for the ordering discrepancy from what you've said.
I'm still not sure whether this could be due just to an offline device syncing an old change very late. Looking back at the history, the edit that appears to have synced later than its marked date (in the current web version) is actually incorporated in subsequent edits (by date, which appear before it in the history timeline). It seems like somehow it was actually synced at the time, but wasn't marked as synced until the later date or something.

**Comment by dmsnell** [comment]
> but wasn't marked as synced until the later date or something.

For technical reasons it's the Simplenote app that records the edit date and there's no timestamp ever given for "this is when the change was sync'd."

Note too that if a device tries to sync its content and discovers that the edit cannot apply cleanly (for example, on device A `cat` was changed to `bat` while on device B `cat` was changed to `rat`) then it will tell the server to adopt its changes as the new real copy of the note.

In these cases you'll find a revision for the old content right behind the edit. This is to prevent such a conflicting edit from causing you to lose your data.
