### ISSUE TITLE
Notes not syncing and Restore Note not working in V. 1.12.0

### ISSUE THREAD

**Issue by lagerratrobe** [Automattic/simplenote-electron#1841]
Guys, this is really frustrating and this is not the 1st time this has happened.  If I can't rely on my edits getting saved, I'm hosed.  Can you please add some force-syncing option that will will not update a note's version unless there is confirmation the change has syncc'ed - or something?  It's clear that the desktop app is not syncing reliably to the Web right now.

### Expected
I expect the that the note I'm working on saves to the last version in which anything was written.  Also, I expect that when I use the History function (to set the note back to a snapshot in time), that using the "Restore Note" button will reset the note to that version. 

### Observed
I am repeatedly seeing the note I'm currently working on revert back to an older snapshot, without my intervention.  When I look back through the history and select the version that had my last changes (from 3 days ago), that version stays on my screen - until I try to edit it, at which point it reverts.

Note from 4 days ago: (Good)

<img width="959" alt="good_note" src="https://user-images.githubusercontent.com/686797/72545391-d0796a80-383d-11ea-9055-05e2be038f7d.png">

Current (Bad):

<img width="1045" alt="bad_note" src="https://user-images.githubusercontent.com/686797/72545434-de2ef000-383d-11ea-8945-386b9b4fa237.png">

### System info.
Windows 10, V. 1.12.0 of the app.

**Comment by xylltch** [comment]
I have observed the same behavior.  I have not had issues with syncing between the Android or Web clients, but Windows 1.12.0 is unreliable.  It does not always pull down changes that have been made via Android or Web clients (and I can verify that those have synced properly because the note contents are identical.

For example, I just opened the Windows client and observed that my note did not reflect the changes that had been made via the Web client earlier.  The last update for the note in question happened on Jan 18, 2020 5:40 PM, but the Windows client had reverted that note to a much earlier version from Jan 17, 2020 11:30 PM.  This was not simply the previous version, but 27 versions out-of-date.  The correct version that should have been pulled down was from Jan 18, 2020 6:35 PM.

I observed similar behavior as the other user, where the contents of the note did change and reflect the correct contents when the slider was positioned at the latest version and after clicking the "Restore Note" button, but as soon as I interacted with the note in any way (clicking mouse cursor inside the text field, scrolling the window) the note would immediately revert to the incorrect version from Jan 17, 2020 11:30 PM.

My current workaround is to open the web client, copy the entire contents of the note from the correct version, then paste and overwrite the note in the Windows client.  This seems to fix the issue for a time, but I have had this problem every few days across 3 different Windows devices.

**Comment by sshaikh** [comment]
If there is a refusal to fix this the at least provide some status to tell us syncing didn't happen. Knowing that much would be a massive improvement and allow us to adjust our workflow as required.

**Comment by dmsnell** [comment]
Hi @sshaikh 👋 

It would be really silly for us to refuse to fix a bug that's central to how our app works wouldn't it 🙃 

More likely the case is that we're not perfect and we missed this issue when trying to understand it. We had some bugs related to the history/revision slider and we fixed them in 1.14.

For any party involved here can you confirm if you are still having the same problem in the newer versions of the app? 1.14 is out and 1.15 is in beta release. I'm going to close the issue because I believe that the bug reported was resolved in 1.14 but we can reopen if we've missed something.

**Comment by KshDi13** [comment]
**Similar issues.** Make a change to a note on _Android_ (2.7) and when open the same note on _Windows_ (1.17.0) the note has NOT updated. Now i know enough (due to having come across this issue now numerous times) NOT to edit this out of date note on _Windows_ as this will render this the latest note and my changes i made to the note on _Android_ will be lost somewhere (and not findable in history). If i come out of the note on _Windows_ and go into another note and then back into the offending note SOMETIMES this shows the edits that i had made in android BUT i cannot guarantee this and most times it doesn't. What i find most effective is if i have the note open in _Windows_ (say currently showing out of date note) and then open the app on _Android_ (not even go into the note), suddenly i watch on my _Windows_, the note being updated in real time.

Also i know by experience NOT to simple edit a note in _Windows_, and leave it open as then _Android_ will struggle to be up to date. Best solution for me is to always come out of the note when edited in _Windows_ then _Android_ tends to be up to date when i look at that same note later.

**Comment by sshaikh** [comment]
> Hi @sshaikh 
> 
> It would be really silly for us to refuse to fix a bug that's central to how our app works wouldn't it 

Maybe. I have no idea if these are old or new bugs but I've had these problems since I started using the app close to when it was launched. I've seen it at least once on 2.7.

But it's the same refusal to add repeatedly requested and real quality of life additions like a visible "last saved date" or a "save status" that leads me to wonder if you even believe us when we tell you about our experiences.

I get that it's a hard problem to solve (if at all fully solvable), but that's why sometimes you need to break whatever pure vision the software had at the start. So let me try making the case again:

The history has a log of updates. Making the latest date visible will give us confidence in exiting the instance that we're using - and not to fork our note until it has. I'm baffled as to why there's so much resistance to this, and am hoping the now countless experiences of people losing note versions will get you on our side, because frankly simplenote still does a whole bunch of things right that other note taking apps don't.

Until then I guess I'll have to continue being anxious and guarded using it.

**Comment by sshaikh** [comment]
Gosh I take it back. This is exciting: https://github.com/Automattic/simplenote-electron/issues/2162
