### ISSUE TITLE
Using Spellcheck in Firefox replaces text at top of note

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-electron#1868]
### Expected
When I click to accept a suggestion from spell checker to correct a misspelling only that word should be changed. No other text in the note should be affected. 

### Observed
If using spell check to correct a word is the first action you take in a note the title of the note will be replaced with the text of the line you're correcting.

### Reproduced
1. Open a new note 
2. Add text that includes a misspelling
3. Open a different note
4. Click back to the note and immediately correct the misspelling using the auto suggestion of the spellchecker

![](https://d.pr/i/pYv26T+)

(Image link: https://d.pr/i/pYv26T )

Reproduced
Firefox 72.0.2 | MacOSX 10.15.2
User reported
Firefox 72.0.2 | MacOSX 10.14.6
#2662776-zen

**Comment by codebykat** [comment]
I just reproduced this and can I just say WHAT the actual WHAT

It does seem necessary to switch to a different note and then switch back in order to trigger it.

Also, if you hit Undo, weird things happen. It seemed to undo the title change but not the original misspelling; when I switched away from the note and back, the original misspelling was back.

Firefox 79.0 | MacOSX 10.15.6

**Comment by belcherj** [comment]
This was from the before 2.0.0 closing as it can no longer occur.
