### ISSUE TITLE
Code elements are hard to distinguish

### ISSUE THREAD

**Issue by qualitymanifest** [Automattic/simplenote-electron#1891]
\`code markdown\` is hard to distinguish from the rest of the text. The font is definitely different from regular text but it can be hard to pick out. Giving it a little `background color` would make it easy to locate. Alternatively the iOS app uses a gray font color for code, which works too.

**Comment by happybridge14-totoro** [comment]
I met the same problem and have done some research on it. The application use "showdown" to turn markdown format to HTML tags. The code blocks are translated to `<pre><code></code><pre>` and inline codes are translated to `<code></code>`. The application then uses `highlight.js` to apply colors to the codes. Here are two issues here:
1. The application is not applying `highlight.js` in the first case. Only the second case is considered.
2. It seems that `highlight.js` itself can only apply colors to block elements because the CSS writes `.hljs {display:block}`. Use CSS: `.hljs-addition {display: inline-block}` is a workaround, but it might not be the perfect fix.

**Comment by belcherj** [comment]
<img width="832" alt="Screen Shot 2021-03-01 at 11 15 46 AM" src="https://user-images.githubusercontent.com/6817400/109525394-7d816780-7a7f-11eb-800f-54307f34cb9f.png">

**Comment by belcherj** [comment]
https://highlightjs.org/ Do we want to pick a new theme for code blocks in light and dark mode?

**Comment by dcalhoun** [comment]
@SylvesterWilmott I'd appreciate your input on how we would like to approach this from a design perspective. We could either (A) apply a simple background color or (B) apply syntax highlighting to inline code. Note that this is not about _code blocks_, but _inline code_. The former will remain as-is.

| (A) Simple Background Color | (B) Syntax Highlighting |
| --- | --- |
| <img width="801" alt="inline-code-background" src="https://user-images.githubusercontent.com/438664/110507015-3f122b00-80c5-11eb-91a7-0b8983bb36d7.png"> | <img width="763" alt="inline-code-highlighting" src="https://user-images.githubusercontent.com/438664/110507040-45080c00-80c5-11eb-803f-9ef457f18903.png"> |

My opinion is that we should pursue option A because (1) inline code blocks do not support setting a language manually (and thus you are completely dependent upon its ability to accurately detect the correct language) and (2) that is the practice I've seen other Markdown tools apply. For either option, we would apply a different color based upon the user's preferred theme (i.e. light or dark).

What do you think?

**Comment by SylvesterWilmott** [comment]
Thanks @dcalhoun 

I agree that the inline blocks should remain without syntax highlighting. The proposed style using the monospace typeface and background looks great to me!

With regards to the colour, I think using the same colour as the tag background (in the editor) would be great.

**Comment by dcalhoun** [comment]
@SylvesterWilmott sounds good. I'll update the background color to match the tags. Thanks!
