### ISSUE TITLE
Explicit sync

### ISSUE THREAD

**Issue by Deleplace** [Automattic/simplenote-electron#1897]
### What
A "synchronize now" button, and an indicator of success/failure.

#### Preamble
I've been using this nice service for several years on many devices. It is very useful for me. Thank you so much to the whole team!

#### Problem
Synchronization between client and server sometimes fails. Some new notes are not uploaded, some recent notes are not imported, and we have no indicator to know if the client is "currently" (i.e. reasonably recently) up-to-date with the server, or not. With 2 clients open, we don't know which one is failing.

#### Disclaimer
Managing a distributed state is no picnic. I totally acknowledge that it is hard to guarantee that the state of an open client (currently in use) is _always_ the same as the state of the server.

#### Tradeoff
In an ideal world, we don't need any bloated UI overhead for this : sync always succeeds and client data is always up-to-date with server data (in both directions). Fewer widgets is better. And this works indeed, most of the time!

When it doesn't, it would be very useful for me to:
- have the client acknowledge that is has not been able to sync for more than one minute (e.g. an orange bullet instead of green bullet),
- let me explicitly "try again" to sync,
- if the explicit action fails, then it's the right time to display an error message with a plausible cause (e.g. "connectivity problem" is not the same as "encountered corrupt data")

I call this a difficult tradeoff as it's simultaneously about confessing that things are going wrong, and adding complexity to mitigate the problem with a "better degraded experience".

I emphasize that this is very different from "fixing all the existing synchronization bugs". Fixing the bugs is of course useful, but IMO it's important to acknowledge that sync problems will always exist (e.g. internet connectivity issues) and still make the app as useful as it can be.

**Comment by Deleplace** [comment]
This problem is the same with all client distributions, and the suggested feature is similar.

However the implementation would live in different repos for different clients, which is why I created the same issue:
- in [simplenote-electron #1897](https://github.com/Automattic/simplenote-electron/issues/1897)
- in [simplenote-ios #639](https://github.com/Automattic/simplenote-ios/issues/639)
- in [simplenote-android #945](https://github.com/Automattic/simplenote-android/issues/945)

**Comment by dmsnell** [comment]
Thanks @Deleplace - I'm going to close this here and defer to the answer given in Automattic/simplenote-ios#639

> I call this a difficult tradeoff as it's simultaneously about confessing that things are going wrong, and adding complexity to mitigate the problem with a "better degraded experience".

Personally I don't see this as much of a tradeoff since Simplenote is designed to work _in and out of connectivity_. That is, if I expect to use the app when the internet comes and goes I don't consider that a failure situation.

We include an indicator of changes that we think may not be synchronized with the server (it's at the bottom of the note list) and we will warn when logging out if there are unsynchronized changes. Maybe some network status visualization could be useful but it's not currently on our radar.

<img width="202" alt="Screen Shot 2020-02-12 at 4 42 52 PM" src="https://user-images.githubusercontent.com/5431237/74387775-bd16dc00-4db6-11ea-9139-43b50f44fe00.png">
<img width="202" alt="Screen Shot 2020-02-12 at 4 42 38 PM" src="https://user-images.githubusercontent.com/5431237/74387776-bdaf7280-4db6-11ea-918f-880224148f05.png">
