### ISSUE TITLE
Notes are overwritten by older versions

### ISSUE THREAD

**Issue by mkeyful** [Automattic/simplenote-electron#1910]
I think I discovered a bug in the simplenote history function: 

My notes are often overwritten by an older versions. 
When checking the history of the note I realized that versions are not listed chronologically. 
That means that the latest version is listed as older version in the note history while older versions appear as latest version. 

See screenshot attached. In this example February 12th comes after February 14th.
[error_history.pdf](https://github.com/Automattic/simplenote-electron/files/4215437/error_history.pdf)

**Comment by dmsnell** [comment]
@mkeyful thanks for reporting. We've been trying to better represent the sequence of edits but having edits non-chronological is in itself not indicative of a problem. These seemingly out-of-order edits can appear when we are editing a note on more than one device and the updates from one occur after the updates from another.

There is a difference therefore between the real physical time that the edits were made (this is was is supposed to show in the revision slider) and the sequence in which those edits were synchronized with the server. If one device goes offline for any appreciable amount of time then it's likely that this swapping occurs.

If you have lost any data or think that something adverse occurred to your notes please contact our support at support@simplenote.com for account-specific help. Otherwise please know that we've been thinking about that time indication and how to better communicate what's actually going on there.

**Comment by mkeyful** [comment]
Hello Dennis,

 

thanks a lot for your reply.

Wouldn't it make sense to change this principle and order the edits chronologically (like Google Tasks for example).

It might be difficult for a user to control when his device synchronizes with the server.

 

I, for example, use simplenote to synchronize between two smartphones and my notes get overwritten by older versions all the time. No way to control this.

 

Best regards

Moritz

 

 

Gesendet: Montag, 17. Februar 2020 um 19:44 Uhr
Von: "Dennis Snell" <notifications@github.com>
An: Automattic/simplenote-electron <simplenote-electron@noreply.github.com>
Cc: mkeyful <moritz.kaiser@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [Automattic/simplenote-electron] Notes are overwritten by older versions (#1910)


@mkeyful thanks for reporting. We've been trying to better represent the sequence of edits but having edits non-chronological is in itself not indicative of a problem. These seemingly out-of-order edits can appear when we are editing a note on more than one device and the updates from one occur after the updates from another.

There is a difference therefore between the real physical time that the edits were made (this is was is supposed to show in the revision slider) and the sequence in which those edits were synchronized with the server. If one device goes offline for any appreciable amount of time then it's likely that this swapping occurs.

If you have lost any data or think that something adverse occurred to your notes please contact our support at support@simplenote.com for account-specific help. Otherwise please know that we've been thinking about that time indication and how to better communicate what's actually going on there.

**Comment by dmsnell** [comment]
> Wouldn't it make sense to change this principle and order the edits chronologically (like Google Tasks for example).

Yep, as much as is possible 🙂

Unfortunately that's a hard problem and we'd have to make considerable work to implement it and even then it wouldn't be perfect because one device's time may be wrong and even if things are ordered in the sequence they occurred then that can result in some pretty confusing note histories.

**Comment by entodoays** [comment]
I had this issue only once, but I think I understood the flaw. I was working on a note on my Android tablet using the app. Without closing the note, I continued working on the same note on my PC using the web app. When I opened Simplenote on my tablet again, the app saved the version of the note as it was when I finished editing the note before. I had to use the history to recover the note.
Probably, there needs to be a condition when opening the app that if there's a note open check if edits have been done and sync if necessary.
