### ISSUE TITLE
Snap gives error "line 314: [: too many arguments"

### ISSUE THREAD

**Issue by ohthehugemanatee** [Automattic/simplenote-electron#1917]
I can't figure out what changed, but suddenly launching Simplenote from `/var/lib/snapd/snap/bin/simplenote` gives me:

```
/snap/simplenote/239/bin/desktop-launch: line 314: [: too many arguments
/snap/simplenote/239/bin/desktop-launch: line 314: [: too many arguments
```

`snap changes simplenote` says nothing has changed (`error: no changes found`), and I can replicate on a fresh reinstall.

### Expected
Running Simplenote does not give POSIX errors.

### Observed
Running Simplenote gives POSIX errors. Line 314 is in the section for managing user links. This could indicate a more serious problem in the bash script.

### Reproduced
1. `snap install simplenote`
2. `simplenote`
3. Observe error. :)

Make|Model|OS Version|App Version
-|-|-|-
Dell |XPS 13|Manjaro current (kernel 5.4.18-1-MANJARO)|1.14.0

**Comment by dmsnell** [comment]
Hi @ohthehugemanatee. Thanks for reporting this. We've had an issue or two with `snap` in the past and unfortunately we don't provide support for it. We're happy to help if someone figures out what's wrong and how to resolve it but we don't have the time available to support `snap` or other distributions' configurations.

Particularly given the `no changes found` message I'm a bit curious if it isn't something in the system running Simplenote vs. being a problem in Simplenote.

You are welcome to share `desktop-launch` and we can review it for you to see if something stands out but otherwise we might not be able to address this. I'm going to close the issue but feel free to reply if you want.
