### ISSUE TITLE
Electron: Cannot log out when you have unsynced notes

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-electron#1940]
On OSX and Linux in the electron app when you have unsynced notes try loggin out.  I clicked delete notes and nothing happens.

**Comment by rachelmcr** [comment]
I tried this on macOS 10.15.4 with Electron v. 1.17.0-beta1. I had unsynced notes and received this prompt:

![Screenshot 2020-05-20 16 46 53](https://user-images.githubusercontent.com/8658164/82467486-9ead3480-9ab9-11ea-80e7-4aa953e0a5c1.png)

I selected "Delete Notes" and was logged out of the app.

I'll leave the issue open since I haven't tested Linux yet, but at least on OSX it seems to be working as expected.

**Comment by dmsnell** [comment]
Should have been resolved by #2066, specifically in 32dad4d40f83b615b9e4ee233f50aa9485e5e67e.

This was broken during an [Electron API change](https://github.com/electron/electron/pull/17298) in [v6.0.0](https://github.com/electron/electron/releases/tag/v6.0.0-beta.1)
In version 1.7.11, which was in use at the time of #702 when we
started showing the message box, the dialog returned a number
to the provided callback for the response value.

When we updated in #1771 we failed to catch the breakage.
