### ISSUE TITLE
Find in page (cmd+f)

### ISSUE THREAD

**Issue by itaysk** [Automattic/simplenote-electron#1954]
### Expected
pressing cmd+f should always search in the current note

### Observed
when the side bar is collapsed, the find textbox is invisible. when it is not collapsed, the search is global.

### Reproduced
1. collapse the sidebar
2. press cmd+f
3. ??

I have opened this as a bug because of the sidebar issue, but I have mentioned the more general issue as well: cmd+f is considered as "find in page", and currently it's unified with global search. these should be distinct from a UX perspective (regardless of the described bug) because the resulting experience is counter intuitive.

**Comment by michaelwexler** [comment]
This is really a problem with workflow.  Notes more than a screen long need search to jump to sections, esp. since sidebar search is only a filter to docs with presence, not actually jumping us to the location.

Since this change, I have not found a way to search in a note in Firefox; app.Simplenote.com keeps grabbing the search keystroke or the "edit: search in this page" menu option on Firefox and forcing a global doc search in the sidebar.  In Chrome, Edit: Find: Find... does actually open a search box, but Cmd-F still is captured.

Can you folks take a look at this?   Cmd F (or Ctrl F for windows) or Edit:Search in this page (for Firefox) from the menu should execute the browser native "in-page" search and should not be overridden.

It is disappointing that Google Docs has also chosen to override find, but I hope Simplenote can be better (:-))

**Comment by dmsnell** [comment]
@itaysk and @michaelwexler we did update the search hotkeys to better conform to platform expectations. <kbd>Ctrl</kbd>+<kbd>F</kbd> now performs the search on the note list while <kbd>Ctrl</kbd>+<kbd>G</kbd> searches within the note.

It was a difficult decision because we don't want to override the browser's native find, but also we didn't want to make things more confusing since the browser's search will return different results than the Simplenote search. For instance, if you search for `tag:tradeoffs keyboard hotkey` using the Simplenote tools you'll jump inside your note to any instances of `keyboard` or `hotkey`. This matches the list of notes returned by the search.

You can also use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>G</kbd> to jump backwards through a note to the previous search result as one might expect.

**Comment by codebykat** [comment]
Closed by #2078

**Comment by itaysk** [comment]
1. I'm with 1.16 and the new Ctrl+G doesn't seem to work. I also tried with CMD+G and the Edit menu only shows 'Search Notes...'. How do I use this find in note feature?

2. The original reason for opening this issue was what happens when sidebar is collapsed and CMD+F. This is still not fixed.

3. I just wanted to say that I fill that this is the wrong solution. Won't you agree that every other program that has CMD+F will search within the currently opened document? I can't think of any other program that changed CMF+F to a global search. Why can't we do the same in Simplenote and have CMD+G (or actually more conventionally CMD+Shift+F) be the global search? Maybe this is just me, in this case I will step down, but I don't think so (maybe we could do a survey or something like that)
