### ISSUE TITLE
When will Simplenote be available as a flatpak?

### ISSUE THREAD

**Issue by Akmadan23** [Automattic/simplenote-electron#2052]

**Comment by codebykat** [comment]
Hi there! We use electron-builder to build our Linux packages, so whenever it gets implemented there (and we upgrade the dependency), it will work for us too. Looks like the issue to track is this one: https://github.com/electron-userland/electron-builder/issues/512

I'm gonna go ahead and close this since we can't take action on it at this time, but thanks for the report!
