### ISSUE TITLE
Third-part  editor support

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [Automattic/simplenote-electron#2053]
### what
***Third-part editor support is important to take advantages of other good editors, such as vscode, atom, vim... I really hope simplenote support to open the markdown notes in other editors.***

### why
***In other editors for coding, I can use snippets to speed up and get a real-time markdown preview, and in the same time to take advantages of simplenote' good organizing function and cross-platform abilities.*** 

### How
***I have no idea about how it will works, but I used Vnote and Notable before, both are markdown-based note taking apps, and they(maybe one of them, I cannot remember clearly) have the function I want.***

**Comment by codebykat** [comment]
Thanks for this request! It's something we're considering but it's not on our immediate roadmap. I think it would involve automating import/export of notes to the file system. I'm closing this issue because we only use Github for tracking active work, but we do take feedback into account when planning upcoming features.
