### ISSUE TITLE
Tag searches are not working as expected

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-electron#2105]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
Search for tag:a, the tag `a` should appear in tag results.
Search for tag:bar, the tag `bar` should appear in the tag results.

### Observed
Neither appear in results

### Reproduced
See expected and screenshots.

<img width="328" alt="Screen Shot 2020-05-18 at 9 05 38 PM" src="https://user-images.githubusercontent.com/6817400/82273420-74d5ff80-994b-11ea-8b54-e009e26063ad.png">
<img width="335" alt="Screen Shot 2020-05-18 at 9 05 12 PM" src="https://user-images.githubusercontent.com/6817400/82273421-74d5ff80-994b-11ea-8bb0-35e6c98454d2.png">
<img width="328" alt="Screen Shot 2020-05-18 at 9 05 02 PM" src="https://user-images.githubusercontent.com/6817400/82273422-756e9600-994b-11ea-828a-974b280ee9ef.png">

OSX|Chrome

**Comment by codebykat** [comment]
This is the intended behavior. If you have already entered a valid tag in the search bar with the `tag:` syntax, the note list is being filtered to notes that have that tag.

If you don't use the `tag:` syntax, it will suggest the tag so as to surface that syntax, and also to allow you to filter to notes that have that tag as well as notes that contain the search string.

We elected not to suggest the tag you've already typed because it would literally... not do anything. When you click on a tag suggestion, literally all it does is replace the search text with `tag:suggestedTag` so if you've already typed that tag in the search bar.. ¯\\_(ツ)_/¯

**Comment by belcherj** [comment]
I get it now.
