### ISSUE TITLE
Adding groups

### ISSUE THREAD

**Issue by mahdiar** [Automattic/simplenote-electron#2128]
Hi!
### What

I think it's a necessary feature that user can manage his/her notes in groups. I know there is tagging but it's not enough. A note may have several tags but it should have a group/s too.  

### Why

Now I use simplenote for different cases like my classes, my task lists, my important URLs and so on. I can use tags for them but there isn't any diffrence among them. Some of them are more important taht can be groups and some of them are rare.  

### How

![Screenshot](https://user-images.githubusercontent.com/935899/83501816-eaa6a300-a4d5-11ea-9153-e3805c09ed8f.png)
)

**Comment by xmha97** [comment]
+1

**Comment by codebykat** [comment]
Hi @mahdiar and @xmha97, thanks for this request. It's already on our list (see #1600 and others).

A workaround that I use for grouping tags is a prefix, for example I might use something like `writing:blog` and `writing:fiction`. You can also group notes with multiple tags, since search lets you look for notes that have both tags on them (so to go with my previous example, a note could be tagged both `writing` and `blog`, and then if I wanted all blog drafts, I would use `tag:writing tag:blog` in the search bar).

We use only Github to track bugs and active work, so I'm closing this, but we appreciate the feedback and we take it into account when planning future features. Cheers.
