### ISSUE TITLE
Surrogate pairs aren't deleted at once (backspace deletes each surrogate separately)

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#2142]
I'm not sure if this is a bug or if it's expected behavior, but it wasn't what I expected. If this is both expected and acceptable we can close the issue.

### Expected

I expect that if I have a surrogate pair in a note, backspacing will delete that pair all at once.

### Observed

When I have a surrogate pair in a note, a single backspace removes the low surrogate (leaving the high surrogate) and I have to backspace again to remove the character entirely.

For example, I started with the light skin tone thumbs up emoji (👍🏻). When I backspace over that emoji, I'm left with the regular, yellow thumbs up emoji (👍). I have to backspace twice to remove the emoji altogether.

### Reproduced

1. Create or open a note.
2. Add a surrogate pair to the note.
3. With the cursor after the surrogate pair, backspace and notice that the high surrogate is still in the note.
4. Backspace again and notice the high surrogate is now removed, as well.

![sn-electron-emoji](https://user-images.githubusercontent.com/8658164/84033124-479bd080-a990-11ea-8462-56e8930f21bd.gif)

Make|Model|OS Version|App Version
-|-|-|-
VirtualBox VM|Windows|10|1.18.0-beta1

**Comment by dmsnell** [comment]
This is odd and I'm not sure how to quickly assess if we'll be able to easily fix it. In some cases I think this could be convenient but it's clearly a bug.

The example on `draftjs`'s own website demonstrates this problem so I guess actually it may not be viable for us to attack the issue. In the branch I've been working on I've replaced `draft-js` entirely with a different editor `Monaco` but sadly that one does it too (and even VSCode does it)

Makes me wonder if this was an intentional choice. It's not a problem with a clear solution of "how should this work."

To that end we're not seeing surrogate pairs being split here actually - these are separate Unicode code points: the thumbs-up Emoji and then a Fitzpatrick skin tone modifier.

https://www.unicode.org/reports/tr51/#Diversity

I have filed bug reports with VSCode and also with draftjs to see if those maintainers might be able to fix the underlying issue.

 - https://github.com/microsoft/vscode/issues/99629
 - https://github.com/facebook/draft-js/issues/1105#issuecomment-640803391

**Comment by dmsnell** [comment]
Also I marked this `wontfix` because we won't likely be able to fix this unless the upstream maintainers update their code, in which case we should benefit automatically.

**Comment by rachelmcr** [comment]
> Makes me wonder if this was an intentional choice. It's not a problem with a clear solution of "how should this work."

Yeah, I wasn't entirely sure what was expected here. I'm fine with closing this issue for now since we'll need to wait for an upstream fix.

> To that end we're not seeing surrogate pairs being split here actually - these are separate Unicode code points: the thumbs-up Emoji and then a Fitzpatrick skin tone modifier.

Thanks for explaining! I think I grok the difference now.
