### ISSUE TITLE
Pin\Password request on startup

### ISSUE THREAD

**Issue by Vfialkin** [Automattic/simplenote-electron#2145]
Android mobile app has a nice feature: pin protection, but the desktop app is open to anyone with access to pc. 

### What
Request pin or password on app startup.

### Why
Security. Now web and mobile versions are more secure than desktop application

### How
a) option in settings to request a password on app startup
b) option to set an extra pin requested on app startup

**Comment by codebykat** [comment]
Hi @Vfialkin, thanks for this suggestion. I've noted it in our feature requests, but to be honest I don't think it will be a high priority for the desktop apps. Depending on the reasoning, there are a lot of workarounds on the desktop:

* Set up multiple accounts on the computer for multiple users instead of sharing apps
* Sign out of the desktop app after using it
* Use the web version at https://app.simplenote.com and either sign out at the end of the session, or configure your browser to delete cookies on close (for fine-grained control there are several browser add-ons that do this)

I'm closing this issue since we only use GitHub for tracking bugs and active work, not long-term ideas -- but we do take feedback into account when planning future work, so I appreciate you taking the time to reach out. Please feel free to update with more details about why this is a need for you.
