### ISSUE TITLE
Tags are not syncing from Windows 10 to Android phone

### ISSUE THREAD

**Issue by dolgelukkig** [Automattic/simplenote-electron#2165]
While doing a Smoke test I noticed the tags I added in my desktop app are not syncing with my phone They seem to disappear. 
I am testing SimpleNote 2.7-rc-1 on Android. My phone is a Samsung Note 8 running on Android 9 and SimpleNote 1.19.0-beta1
### Expected

While a note was open on my phone I was expecting the tags I added to the same note on my desktop to appear in the app on my phone. 

### Observed

While the note was open on both apps nothing changed. When leaving the note on my phone and coming back the tags weren't added to the note and the tags disappeared in the desktop app. 

I tested adding tags to a new note and the issue is not appearing then. 

I tested and repeated the issue on several different notes.

### Reproduced
***(Required)*** 

- open Simplenote desktop app
- open existing note, add tags
- open the same note on Simplenote app on android phone
- tags disappear from the note on desktop.

***(Optional)*** 

![tag disappearing simplenote](https://user-images.githubusercontent.com/5507879/85232705-4e4f2c80-b401-11ea-8682-c9a8c435697d.gif)

***(Optional)*** 

Make|Model|OS Version|App Version

HP Spectre 13 inch | Windows 10 PRO | 1909 | 1.19.0-beta1
Samsung Note 8 | Android 9 | 2.7-rc-1

**Comment by rachelmcr** [comment]
Thanks for the report! This is a bug on the Android side in 2.7-rc-1 where the Android app was reverting tag changes from other clients - it was fixed in https://github.com/Automattic/simplenote-android/pull/1060.

One way to double check this is to make sure the Electron app syncs to the web app at https://app.simplenote.com/ (instead of the Android app). I'll close this issue since the bug was on the Android end, but if you also see an issue with syncing between the Electron app and web app we can reopen this. :)
