### ISSUE TITLE
A Feature Request for WebApp: Add a apple-touch-icon

### ISSUE THREAD

**Issue by xmha97** [Automattic/simplenote-electron#2166]
Firefox is using the apple-touch-icon for the icon of pinned sites
But Simplenote does not use this :(

Firefox Dark
![Firefox Dark](https://user-images.githubusercontent.com/23485114/85318121-b28ef080-b4d4-11ea-9bae-e7e4b1328aec.png)

Firefox Light
![Firefox Light](https://user-images.githubusercontent.com/23485114/85318140-b753a480-b4d4-11ea-872b-47283c573bea.png)

Please add a transparent logo to the Simplenote web app. (like Apple Music)
Thanks.

**Comment by codebykat** [comment]
Hmm this is odd. We have one already, https://app.simplenote.com/apple-touch-icon.png . We don't link to it anywhere specifically, but the [Apple docs](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html) say:

> If no icons are specified using a link element, the website root directory is searched for icons with the apple-touch-icon... prefix. For example, if the appropriate icon size for the device is 58 x 58, the system searches for filenames in the following order:
>    apple-touch-icon-80x80.png
>  apple-touch-icon.png

I'm confused about what platform you're on and how this is different from the favicon. I see the icon on Firefox on both desktop and mobile (iOS):

<img width="366" alt="Screen Shot 2020-06-22 at 1 30 07 PM" src="https://user-images.githubusercontent.com/52152/85332367-af701200-b48c-11ea-8fdb-6cfe7e1e11fe.png">

![IMG_2F751C2D4A16-1](https://user-images.githubusercontent.com/52152/85332421-c7e02c80-b48c-11ea-9584-c879752ce0f7.jpeg)

Can you explain this a little more please?

**Comment by xmha97** [comment]
Hello @codebykat 

Firefox displays site screenshots with its favicon when it doesn't find the site's apple-touch-icon.
I don't have a Mac or iOS and I can't try this on them, but Firefox may work differently on the Mac OS.
For example, use an icon when there is no apple-touch-icon.
This may be true because, in your screenshot, the Simplenote tile logo is low quality:
![Firefox](https://user-images.githubusercontent.com/52152/85332421-c7e02c80-b48c-11ea-9584-c879752ce0f7.jpeg)

All I can say is that this problem only exists with app.simplenote.com, not even simplenote.com:
![Firefox](https://user-images.githubusercontent.com/23485114/85339003-85543980-b4f8-11ea-960f-d4b98e52d7c6.png)

Also, in the app.simplenote.com code, I didn't see anything about the apple-touch-icon, although it is available in simplenote.com. I think that's the problem:
![Firefox](https://user-images.githubusercontent.com/23485114/85340920-44f6ba80-b4fc-11ea-9497-1a4e991a537d.png)

I'm sorry, I'm not a web developer and I can't give you detailed information and I just mentioned my problem.
Thank you for your attention.

**Comment by codebykat** [comment]
Ahh I understand now, thank you. The fact that it's called `apple-touch-icon` made me think you were using Firefox on iOS.

Should have a fix for this soon.

**Comment by codebykat** [comment]
This is done. It worked for me when I added the pinned site, but it did take a few minutes before it showed up, so I guess Firefox caches these or loads them as a background job or something.

We opted not to use a transparent icon as per our design guidelines.

<img width="365" alt="Screen Shot 2020-06-24 at 7 12 05 PM" src="https://user-images.githubusercontent.com/52152/85645454-a038c200-b64e-11ea-8c4a-8615dccbcbb0.png">

**Comment by xmha97** [comment]
For me, this problem exists even after reinstalling Firefox :(
On what operating system did you use Firefox?
![Firefox](https://user-images.githubusercontent.com/23485114/85646806-35b96d80-b6b2-11ea-928b-1bdd9991c321.png)

**Comment by codebykat** [comment]
I'm not sure what to tell you, to be honest. At this point we're trying to debug Firefox rather than Simplenote.

I would give it a day or two to see if that caching expires. I tested on Firefox OSX and it showed like your screenshot for some time (long enough that I was trying to figure out what went wrong) and then it loaded the new icon.

Things I did while trying to get it to work:
- Created a new profile
- Added it to top sites
- Loaded it in another tab
- Clicked "Delete from History" and then "Unpin" -- at that point the icon immediately changed, and I was able to re-pin it.

However, I still can't get the new icon to show up in my original profile, so there's definitely some caching going on somewhere.

I note you still have the old favicon as well. You could try some of the troubleshooting steps here: https://appuals.com/fix-firefox-displaying-the-wrong-bookmark-favicons/

You could also try logging out on app.simplenote.com, clearing your browser cache and cookies, and adding it to pinned sites before logging in again. It's possible it won't pick up the meta tag on a logged-in session.

I finally found Firefox's documentation on this: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/UI_considerations and can confirm that we're now supplying a correctly-sized icon in the `meta` tag as documented there, so I'm not sure what else to suggest.
