### ISSUE TITLE
Undesired tags added to tags list in Linux

### ISSUE THREAD

**Issue by JP2620** [Automattic/simplenote-electron#2198]
### Expected
  When adding a tag that didn't exist before to a note and immediately removing it, it should not appear on the tags list.

### Observed
  The tag appears in the tag list

### Reproduced
> 1. Open a note.
> 2. Add a tag that did not exist before.
> 3. Remove it from the note.
> 4. Check tag list.

### Screenshots

![image](https://user-images.githubusercontent.com/44300242/87252486-eb721380-c449-11ea-825c-f7ee9e8d4ef7.png)

![image](https://user-images.githubusercontent.com/44300242/87252503-03499780-c44a-11ea-83ba-0ae3f9d0ee92.png)

![image](https://user-images.githubusercontent.com/44300242/87252511-1492a400-c44a-11ea-835a-041639ff3a5b.png)

**Comment by msilbers** [comment]
When adding a tag to a note, it's also adding it to your Simplenote account and tags list, so it's not expected behavior that deleting a tag from one note will remove it from everywhere.

So, I'll close this issue, but I've made a note of your desired behavior on our internal feature request tracker
