### ISSUE TITLE
Empty log

### ISSUE THREAD

**Issue by lucamosca1** [Automattic/simplenote-electron#2278]
Try to understand what happen due to issue #2275 I try to give a look to logs from desktop application

### Expected
If I click on help - Get app logs I have a zip file saved on desktop contains the log

### Observed
If I click on help - Get app logs I have a zip file saved on desktop contains an empty log

Observed on Both windows 10 and ubuntu 20.04, latest simplenotes version: 1.21.0

**Comment by dmsnell** [comment]
Hi @lucamosca1 - thanks for reporting this! The application log is new and right now only reports a subset of events, mostly related to the install/update process. I'm going to close this issue since the log as written isn't broken, it's just not recording all the information I think you expect it to. Over time we'll have more and more events going there though.

**Comment by designsimply** [comment]
@dmsnell I tried testing the application log on Windows 10 Simplenote 2.0.0 today and found that it was empty after saving a note and generating a public link for it. Is it still the case that logs wouldn't be generated for those kinds of actions? (Just double checking! I'm asking because a user has reported that generating a public link is not working for them but it's working in my own testing and I thought application logs might help if I could get some.)

**Comment by dmsnell** [comment]
we haven't added any new events to the application log

we can investigate issues publishing notes in support where it's hard to do it in Github. there aren't any available events that we could log, unfortunately, to give more knowledge in the app about failures to generate a public link - this is due to the way that the links are generated behind the scenes
