### ISSUE TITLE
Windows icon

### ISSUE THREAD

**Issue by algent-al** [Automattic/simplenote-electron#2291]
Just installed Simplenote 1.21.1 in a Windows 7 machine and noticed that the icon is pixelated.

![simplenote-icon-windows](https://user-images.githubusercontent.com/46356616/91042098-83e6e080-e611-11ea-82d7-5b72957c1396.png)

The icon quality can be improved.

**Comment by KraXen72** [comment]
![image](https://user-images.githubusercontent.com/21956756/101488742-49a31400-3960-11eb-9ceb-1cb98760f60c.png)
 looks fine for me, i'm in 2.20. update.

**Comment by codebykat** [comment]
Hah, I didn't notice the version number on this report. Thanks @KraXen72. That being said I don't believe the icons have changed since 1.20 (https://github.com/Automattic/simplenote-electron/pull/2158, which should have added the correct icon size for this to be working correctly). @algent-al, please update to the latest version and report back?

**Comment by algent-al** [comment]
Hi! I use Windows 10 now. The icon in this system looks better than in Windows 7.
![simplenote-win10](https://user-images.githubusercontent.com/46356616/101737987-da473480-3ac5-11eb-9d1c-093bba6da04c.png)

**Comment by sandymcfadden** [comment]
I'm going to close this as things seem to be working well on Windows 10. 
Windows 7 no longer being supported by Microsoft so I'd say the impact here should be little.
