### ISSUE TITLE
View menu: inconsistent menu names

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#236]
- `Sort Order` should be `Sort Type`
- Sort Order is missing
- Note Display is missing
- Sort Type options should be 'Last modified`, `Last created`, and `Alphabetical`

Mac OS X 
1.0.1

![screen shot 2016-03-18 at 10 33 28 am](https://cloud.githubusercontent.com/assets/618551/13882807/04d10ab0-ecf5-11e5-9d02-3801aed8e1d6.png)

**Comment by dmsnell** [comment]
I've been working on this and it's quite a mess. I'm running into issues following the control flow after clicking on a menu item and I can't get the notes list to refresh, even after doing things like calling `loadNotes()` and `forceUpdate()`

These issues are somewhat giving me the impression that if we fix the sorting issue (#144) then these problems might be fixed with that PR.
