### ISSUE TITLE
This is not a bug, this is a heartfelt thanks

### ISSUE THREAD

**Issue by ernstki** [Automattic/simplenote-electron#2378]
Thanks, everyone, for keeping this project going. For fixing the bugs but resisting feature creep. For keeping it simple. For keeping the servers up and running, even with no real obvious benefit to Automattic. For syncing my notes day after day after day without a hitch for years. Aeons, really, in Internet time.

It's an improbable accomplishment, worthy of congratulation. This is not the way these things usually pan out, after an acquisition, after a transition to open source, after establishing a public issue tracker that fills up with… well, you know.

Feel free to close this issue after at least one core developer gets to see this, who hasn't been thanked in a while for their (probably unpaid) hard work.

Cheers,
Kevin

**Comment by theck13** [comment]
Your words are more than kind and greatly appreciated.

I can say without hesitation that every single one of the Simplenote developers is _very_ passionate about the apps and we want nothing more than to be good stewards.  We are a crew of few, but we will continue to make Simplenote worthy of your device(s) as long as humanly possible.

It is a privilege to work on Simplenote.  We are extremely grateful for users like you.  Thank _you_!

**Comment by codebykat** [comment]
I can't think of anything to say that @theck13 hasn't already said so well. I love Simplenote, and I've used it myself for years, for almost everything, from grocery lists to journaling. I feel lucky that I get to help keep it running smoothly and make it better! Thanks @ernstki for taking the time to write these kind words, I think you made everyone's day 😁

**Comment by ernstki** [comment]
High-fives and kudos all around!

Now if I could squander this little bit of good will I've built up and let's talk about this feature request I'm KIDDING.

Kidding!

**Comment by dmsnell** [comment]
@ernstki thanks so much for taking the time to share your thoughts. In fact all of us core developers are paid by Automattic to build the product but we are also avid Simplenote lovers ourselves. several of us spent a few years working on it in addition to our normal work because we love it and because of people like you who make it feel worthwhile to improve the product.

> after establishing a public issue tracker that fills up with… well, you know.

It's easy to chuckle at this because you clearly understand how it works - our bug tracker fills up (along with legitimate bug reports) with demands that we implement some particular feature, anger that we haven't fixed a specific bug, and lots of issues that take considerable time to try and diagnose and fix and often result in a dead-end.

We're people just like anyone else and for a product that generates no income (we don't charge people to use it and we don't sell any of our customers' data or any derivatives of it) the human aspect remains a strong motivator. People appreciate appreciation. We'll keep on trying to honor your respect with updates that increase the reliability of your notes while thoughtfully adding features that work towards the goal of simple note-taking. We'll make missteps at times and we'll go back on decisions we realize were wrong but we believe in that vision of an open, simple, and reliable way to write and read notes on any device.

**Comment by ernstki** [comment]
Thanks, everyone. Your responses were thoughtful and memorable, and make me feel _even better_ about being a sometime-subscriber, long-time user, and an advocate for Simplenote.

Particularly the "stewardship" aspect you emphasize, because there is something so old-fashioned and comforting about hearing that word from developers at a software and services company, as opposed to, say, the more _à la mode_ buzzwords of our time, like "conversion," or "user engagement," or "integrations," or "exit strategy."

In the interest of good housekeeping, I'm closing the issue, as it has been fully resolved according to its original scope.

Take care.

—Kevin
