### ISSUE TITLE
Simplenote is showing a warning prompt while closing Firefox tab

### ISSUE THREAD

**Issue by equasman** [Automattic/simplenote-electron#2380]
### Expected

Simplenote opened in Firefox shouldn't show any warning of losing data if my data is already synced to the server.
### Observed

Firefox shows a warning prompt while closing the Simplenote tab. Please see the screenshot attached.
![Screenshot_2020-10-02_22-13-23](https://user-images.githubusercontent.com/61104876/94945973-4c673000-04fd-11eb-852c-2c202e4a2dc7.png)
### Reproduced

I'm seeing this warning prompt for the past few weeks every time I want to close the Simplenote tab on Firefox. I tried Chromium and didn't face this issue in that browser.

### Where did you see the bug

- System Make: HP
- System Model: Elitebook 8460p
- OS: Xubuntu
- OS version: 20.04
- Browser: Firefox
- Browser version: 81
- Simplenote app version: Simplenote web, version 2.0.0.-rc5

**Comment by dmsnell** [comment]
@equasman thanks for writing in. Feel free to contact our support for specifics on your account but I would wager that there is some data in your account not synchronized with the server. It can be helpful to look for the 🔄 in the note list and also to look in the trash. If you find a stuck note then you should be able to clear it by making any change, such as adding a space or a newline.

Another option is to go to *Settings* and click on *Logout*. It should open a dialog and tell you which notes are unsynchronized and it should attempt to force-synchronize that note and clear the warning. If it does actually logout without opening the dialog then you can be assured that your data is synchronized and you shouldn't see that warning anymore.

Unfortunately the browsers have removed our ability to communicate through that warning and all we can do is have the browser show its default warning. They removed our ability to add our own information because some malicious parties were causing trouble with that - usually ads trying to prevent people from leaving - even though we never did that with Simplenote.
