### ISSUE TITLE
Markdown file import: Missing last letter of filename

### ISSUE THREAD

**Issue by Sandkorner** [Automattic/simplenote-electron#2398]
### Expected
Expected the filename to be intact as the title of the note.

### Observed
Last letter from filename is unfortunately missing.

### Reproduced
![bugrepor](https://user-images.githubusercontent.com/71094068/96297926-50fe0f00-0ffa-11eb-8b88-7d2a723952ea.gif)

### Where did you see the bug
- OS: Windows 10 Pro
- OS version: 2004
- Simplenote app version: 2.0.0-beta1

**Comment by arpitbatra123** [comment]
I think I have been able to find the cause of this issue, but I can't get the local build ( created using `make package-osx` ) to work. Clicking on `Plain text` just crashes the app with the following error on the console:
![image](https://user-images.githubusercontent.com/21967563/96478358-3673a200-1255-11eb-9157-d083a30164a6.png)

Anyways, The following piece of code in the source is meant to clip `.txt` from the file name, but in the current issue, the file's extension is `.md` and therefore extra characters get trimmed.

```js
        // Trim the .txt extension from the file name
        const fileTitle = file.name.slice(0, -4);
```

 Furthermore, the same file (`simplenote-electron/lib/utils/import/text-files/index.ts`) also has some code to not go through with the file import if it does not have an extension of `.txt` but that is probably not working since the issue creator was able to import an `.md` successfully so that also needs to be looked at.
