### ISSUE TITLE
Package Simplenote as a flatpak

### ISSUE THREAD

**Issue by rhjhunt** [Automattic/simplenote-electron#2431]
### What

I would like to request that Simplenote could be packaged as a [flatpak](https://www.flatpak.org/) and made available on [flathub](https://flathub.org/home). Or if there is no interest in the project for providing a flatpak of Simplenote and if you would not have any objection I would like to provide a flatpak bundle to be installed from [flathub](https://flathub.org/home).

### Why

Packaging as a flatpak allows for an application to be deployed across various distributions and versions of Linux without the requirement for extra package dependencies, as all the dependencies are bundled in the flatpak.

It also allows for easy installation as the Gnome Software package is integrated with [flathub](https://flathub.org/home), allowing applications such as Simplenote to appear in the software catalog and easily installed with the click of a button.

Also, for those running immutable systems and aren't using traditional packages such as RPM packages, it provides a simple method to install great applications such as Simplenote.

### How

I have a working build that you can verify.

```console
$ git clone https://github.com/rhjhunt/flathub.git
$ cd flathub/
$ git checkout com.simplenote.Simplenote
$ git submodule update --init shared-modules
```

You can follow these steps to setup flatpak for the respective Linux distribution https://flatpak.org/setup/ also ensure to install the `flatpak-builder` package.

You can then verify that the flatpak builds successfully.

```console
$ flatpak-builder build com.simplenote.Simplenote.yaml
```

Then install the flatpak to the user home directory.

```console
$ rm -rf build/
$ flatpak-builder --user --install build com.simplenote.Simplenote.yaml
```
The Simplenote package will then be launchable like other GUI applications for your Linux distribution.

**Comment by dmsnell** [comment]
This is awesome @rhjhunt! Thanks for putting in all this work. Do you have any plans for keeping the package updated with our releases?

We haven't made a Flatpak release because we haven't had it in our availability to write the PRs and maintain them, or support the Flatpak release.

On the other hand I don't think any of us will object to having another person take ownership of that. I'll give the rest of the team some chance to respond here as well.

**Comment by rhjhunt** [comment]
@dmsnell honestly I'm going to package it for at least myself, huge kudos to you and everyone that develops and supports simplenote, I love the application.

I would plan to keep it updated with your releases. If there is no objection from the team I'd love to maintain the packaging of the flatpak for flathub.org.

Let me know if there are any questions or concerns before I proceed.

**Comment by nedrichards** [comment]
Hi there, I'm one of the flathub admins. I've merged @rhjhunt's work into flathub and invited @dmsnell to the repo as well - there's no obligation but it does mean that you can take charge if you wish. If there's anyone else from upstream who wants to be involved then let us know and we will gladly add them ASAP.

**Comment by David-Else** [comment]
Hi, I just installed the flatpak 2.0.0 on Linux and `ctrl-shift+i` to insert note opens the web developer tools. Is this a bug in the Flatpak version? Cheers.

**Comment by rhjhunt** [comment]
@David-Else I just tested on a non-flatpak version 2.0.0 and the same issue exists there. Looks like `ctlr+shift+I` is also mapped to the 'Debugging Console'. There is a new issue opened to track this #2436.

**Comment by dmsnell** [comment]
thanks @rhjhunt and @nedrichards - I just returned from some vacation and will accept the invite. I think @belcherj might make a more appropriate maintainer than I would but we share our duties 😄 

@rhjhunt you are doing everything a huge favor, not just yourself. please accept our gratitude for doing this and for being willing to maintain the flatpak.

I'm closing this issue since I don't think anything remains as needs from us. please correct me if I'm wrong and you do.

**Comment by nedrichards** [comment]
I've sent an invitation to @belcherj as well. Thanks all!

**Comment by belcherj** [comment]
Thanks for all the work. We are hoping to get the ctlr+shift+I fix out in the next version.
