### ISSUE TITLE
ARM64 version of 2.0.0 similar to Simplenote-linux-1.20.0-arm64.deb

### ISSUE THREAD

**Issue by rekab72** [Automattic/simplenote-electron#2452]
Can you please add an Arm 7 64 build for the latest major build similar to your effort in 1.20.0 - Simplenote-linux-1.20.0-arm64.deb OR please add instructions to build as I trying to learn by doing after researching examples.

**Comment by dmsnell** [comment]
hi @rekab72 - sorry for removing this. we'll try and get on it. it was removed in the lineup to 2.0.0 because (sadly) it broke the build again and we were focusing on getting that release ready and don't have as much experience with the ARM builds.

linking to #2042

**Comment by rekab72** [comment]
@dmsnell thanks, understand priority and using 1.2.1 works on Pi 4 8GB 20.10 Ubuntu Mate image, no issues. Just would like to keep up with fixes/features and expect as Apple goes to Arm you'll need a working version.

**Comment by SpacingBat3** [comment]
Seems it is runnable with the `npm run dev` on the ARM64:
![image](https://user-images.githubusercontent.com/57194920/98462088-aec4e780-21b1-11eb-808b-8eb50816fac3.png)
I believe it is possible to package it in an `tar.gz` archive, but I'm gonna check this right now to make it sure...
If yes, I'll do a quick PR to this repo with an updated list of supported architectures in the [`electron-builder.json`](../blob/master/electron-builder.json)...

As for myself, I've never compiled the `deb` archive with the `arm64` host machine using the `electron-builder`, but it might be possible to do on the `x86`/`x86_64` hosts (it's impossible on the ARM64 hosts right now because `electron-builder` uses some X86 binaries to package electron apps in the DEB file)...

**Comment by SpacingBat3** [comment]
@dmsnell can confirm it is also possible to package in `tar.gz` archive with no issues...
In my opinion this also should work for the armv7l architectures...

Check the #2456.

**Comment by belcherj** [comment]
Merged in #2456!
