### ISSUE TITLE
Update from 2.0.0 to 2.1 does not start | not available from Microsoft Store

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#2478]
### Expected
Update from 2.0.0 to 2.1.0 to start as in previous versions (1.x)

### Observed
I have two Windows 10 PC's (office and home)

_________________
(1) Office
- installed with installation file

![Simplenote Update 2 Plus_Gc](https://user-images.githubusercontent.com/22197180/99376822-bd07b780-28c5-11eb-9f52-65f357b9796a.JPG)

![Simplenote Update 2 Plus_Gb](https://user-images.githubusercontent.com/22197180/99376837-c2650200-28c5-11eb-9b17-3be2a473a18c.JPG)

![Simplenote Update 2 Plus_Ga](https://user-images.githubusercontent.com/22197180/99376838-c3962f00-28c5-11eb-8e6e-dc449877346e.JPG)

![Simplenote Update 2 Plus_Gd](https://user-images.githubusercontent.com/22197180/99376850-c6911f80-28c5-11eb-9fc1-26dadae229e1.JPG)
---> blank Window, disappears after few seconds

 
_________________
(2) Home
- Installed from Microsoft Store

![Simplenote ZH 2 0](https://user-images.githubusercontent.com/22197180/99376932-e1fc2a80-28c5-11eb-99d5-3176444cfd2c.JPG)

![Simplenote ZH kein Update](https://user-images.githubusercontent.com/22197180/99376942-e4f71b00-28c5-11eb-80e4-051702cc62ae.JPG)
---> Update not available, Update does not happen (even after Windows restarts)
---> Microsoft Store does not tell wihich version is installed and which version is availble

### Reproduced
see above

### Where did you see the bug
see above

**Comment by PremPatel8** [comment]
I am also having this same issue since the last few Simplenote updates. Every time I open Simplenote I get the "Update Available" prompt, but when I click on "Update & Restart" nothing happens. The only way I can update is by downloading the installer and manually installing the latest version. This bug would be less annoying if we could just turn off the "Check for updates on app start" functionality like in most other apps, since I don't really care to update Simplenote frequently anyways. Hope they can either fix this update bug or at least add a option to disable automatic update checking in Preferences.

Windows 10 version: 1909 (OS Build 18363.1198)
Simplenote version: 2.0.0

**Comment by codebykat** [comment]
Thanks for this info. This is already tracked in #2251 -- we've fixed one issue with the updater in 2.1, but I believe there is still at least one problem with it. I'll add the comment about disabling update prompts over there as well.

For the Windows Store issue, you should be able to see the version in About.

**Comment by Geoffro1611** [comment]
This issue still exists
