### ISSUE TITLE
Web app: Paste option not on Right Click Menu

### ISSUE THREAD

**Issue by poojashetty18** [Automattic/simplenote-electron#2487]
### Expected
Paste option should be available after copying a text

### Observed
No paste option available on right-click menu

### Reproduced
1. Go to https://app.simplenote.com/
2. Add some text or use any existing text
3. Right-click menu and select the text to copy it
4. Go to a new line or enter space and then right-click menu 
5. No paste option visible

![Screen Capture on 2020-11-24 at 10-48-39](https://user-images.githubusercontent.com/44837596/100058599-0bc3cd00-2e43-11eb-8241-6afca9498575.gif)

### Where did you see the bug
- System Make: Apple
- System Model: MacBook Pro 15-inch
- OS: MacOS Catalina
- OS version: 10.15.7
- Browser (if applicable): Chrome
- Browser version (if applicable): 86.0.4240.198 
- Simplenote app version: 2.0.0

Originally reported in 3511566-zen.

**Comment by codebykat** [comment]
Thanks for the report, @poojashetty18. This is a known issue and a limitation of the editor component we're using. Unfortunately it's a security feature in the browser in order to prevent apps from stealing the contents of your clipboard without your knowledge, so we can't really work around it. You should still be able to paste using the keyboard shortcut (Cmd+V) or the menu bar (Edit->Paste).

Upstream reports include https://github.com/microsoft/monaco-editor/issues/1674, but sadly it's not likely this will ever be supported (unless we do another major rewrite of the app and change out the editor component again).
