### ISSUE TITLE
Add archive feature

### ISSUE THREAD

**Issue by Symbitic** [Automattic/simplenote-electron#2499]
### What
I've started working on a fork that adds the Archive feature, similar to what was previously requested in #1740 and #601. 

### Why
The idea is that notes can be stored so that they will be excluded from the notes list and optionally excluded from searches, without the danger of accidentally deleting them forever. It's a useful feature for notes that you don't want cluttering up the tags and notes list views, but you also know you may need again.

### How
I'm working on my own fork. Code wise, it's basically copying much of the code for trash except sending notes to the archive, not the trash.

But first: both previous issues requesting this feature were closed without comment. I'm willing to work on this feature myself, but would it even be accepted in the first place?

**Comment by codebykat** [comment]
Thanks for asking this, @Symbitic. Good question! The prior issues were closed without comment because we don't use GitHub for tracking feature requests (which we may or may not get to eventually); we have an internal list that we refer back to when planning our roadmap for upcoming work. We usually do try to leave a comment to that effect, but sometimes we're triaging a bunch of open issues at once and we don't. 😅 

One problem with adding an archive feature is that we would need it to be implemented on the mobile and OSX apps as well, as feature parity for big changes like this is pretty important. So this may require a bit more of a concerted effort.

I'm not sure how far you are with your fork, but you may have already realized that copying the front-end trash code is only part of the solution... we'd likely need to add another system tag to the notes, so that the "archived" status would also sync to the backend (and thus to the other apps).

My feeling about this particular feature and why we haven't prioritized it thus far is that it may actually be a bit redundant, because for most practical purposes, it's already the way the Trash functions. We tend to be leery of adding complexity to the app.

But, let me pull in our designer for a second opinion. @SylvesterWilmott, do we have any designs or thoughts about implementing this?

**Comment by SylvesterWilmott** [comment]
Thanks @Symbitic !

As @codebykat mentioned, our Trash currently works in the same way as the proposed behaviour for Archive. It certainly wouldn't hurt the experience to have an archive but this may be as simple as changing our "Trash" terminology to "Archive" terminology to communicate that trashed notes are not immediately deleted.

One more thing to point out is that Electron currently allows permanent deletion of a note without a confirmation. Adding a confirmation dialog here would mitigate the chance of accidental deletions you mentioned.

**Comment by Symbitic** [comment]
@SylvesterWilmott in that case, you can close this request.
