### ISSUE TITLE
Left sidebar / navigation bar - enhancements & fixes

### ISSUE THREAD

**Issue by djordjeandrejevic** [Automattic/simplenote-electron#2504]
I have a few suggestions for the left sidebar / navigation bar to make it look better.

All of the CSS suggestions below were done using Debugging Console (Simplenote 2.2.0 / Ubuntu 18.04 LTS).

1. **Less white space** between All Notes / Trash / Settings and the top.
```
.navigation-bar {
  padding-top: 12px;
}
```
2. **Smaller font** for Tags.
```
.tag-list-item {
  font-size: 14px;
}
```
3. **Smaller border width** for All Notes / Trash / Settings and Tags.
```
.navigation-bar-item .button {
  width: 90%;
}

.tag-list-item {
  width: 95%;
}
```
4. **Pointer cursor** when hovering Tags. Currently it's set to text cursor, similar issue to [this one](https://github.com/Automattic/simplenote-electron/issues/2185). I haven't fixed it though, but I assume it has to do something with `.tag-list-item:hover` and then `cursor: pointer;`.

### Old
![2020-12-03_12-18](https://user-images.githubusercontent.com/8862464/101007524-be8ddc80-3561-11eb-852c-6d9b0fd4bb32.png)

### New
![2020-12-03_12-16](https://user-images.githubusercontent.com/8862464/101006606-7c649b00-3561-11eb-92f4-25ae1ea8b077.png)

**Comment by sandymcfadden** [comment]
Thank you so much for taking the time to come up with these changes and provide the CSS code. Really cool.

We have a few open issues right now that we are working and will be working on to update the UI and there are changes included for the area you are looking at here.

I've added the forth point you mentioned to this issue so we can address it there https://github.com/Automattic/simplenote-electron/issues/2566

This issue is going to be changing the left sidebar as well https://github.com/Automattic/simplenote-electron/issues/2562

I'm going to close this issue for now in light of the work we have planned already. Thanks again!
