### ISSUE TITLE
Broken shortcuts due to Monaco upgrade >:(

### ISSUE THREAD

**Issue by mokagio** [Automattic/simplenote-electron#2600]
### Expected
Pressing <kbd>Cmd Z</kbd> or clicking Edit > Undo should undo the last operation in the stack. E.g.: if I delete a word, undo should make it reappear.

### Observed
On macOS version 2.6.0-beta1, neither the keyboard shortcut nor the menu item work

### Reproduced

1. Launch version 2.6.0-beta1 on macOS
2. Open a note and do something on it, e.g: delete a word
2. Hit <kbd>Cmd Z</kbd>
3. Notice how the word does not reappear
3. Repeat by selecting Edit > Undo

https://user-images.githubusercontent.com/1218433/105930986-878a0200-609e-11eb-9638-4eb4180161b2.mov

_You can't see me hitting <kbd>Cmd Z</kbd> in the video, but you can see the Edit menu item highlighting as a result._

### Where did you see the bug

- System Make: Apple
- System Model: MacBook Pro 16" Late 2019
- OS version: Catalina 10.15.7
- Simplenote app version: 2.6.0-beta1

**Comment by codebykat** [comment]
Ugh okay I found this. It is due to #2575 and has been reported upstream to Monaco. Apparently something broke these handlers in 0.21.1 and onward.

https://github.com/microsoft/monaco-editor/issues/2247
https://github.com/microsoft/monaco-editor/issues/2195

I will look tomorrow whether it makes more sense to revert this dependencies bump or add [workarounds](https://github.com/microsoft/monaco-editor/issues/2195#issuecomment-711471692) for these shortcuts. Right now I'm leaning toward the former as I'm not sure what all is missing.

**Comment by codebykat** [comment]
[monaco-editor](https://www.npmjs.com/package/monaco-editor)@0.21.3, released 9 days ago, does not contain a fix.

**Comment by codebykat** [comment]
#2604, #2606
