### ISSUE TITLE
markdown emoji

### ISSUE THREAD

**Issue by Ryannnkl** [Automattic/simplenote-electron#2644]
### What
Maybe it would be nice to put emojis using markdown, like ``:star:`` :star: or ``:coffee:`` :coffee:, since using markdown would maintain a good compatibility with README.md of projects on github 

### Why
practicality of putting the emoji in a DE that does not have an emoji management app, like XFCE, and also makes you familiar with who organizes the readme of projects that use this

**Comment by codebykat** [comment]
Thanks @Ryannnkl 😄 This is a cool idea. I actually use [text expansion](https://www.lifehacker.com.au/2016/07/add-slack-style-emoji-substitutions-to-your-mac/) to get this functionality everywhere on my Mac! I recommend that as a workaround for now.

Closing this for the moment since it's not on our immediate roadmap, but I'll add it to our feature requests for possible consideration in the future.
