### ISSUE TITLE
E-mail verification keeps popping up at start

### ISSUE THREAD

**Issue by piskunow** [Automattic/simplenote-electron#2675]
The simplenote-electronn app version 2.6.0 running on Ubuntu 20.04 keeps asking to verify the email. I did it many times, the request to verify just appears every time I run the app again, even withing the same Ubuntu log-in session.

**Comment by codebykat** [comment]
Hi @piskunow, sorry for the trouble. Do you see the popup if you log in on the web at app.simplenote.com as well?

If not (this confirms that you are successfully verified), can you please try logging out of the app and back in again and let me know if that fixes the issue?

(Also reported in #2663, leaving this open since the other is now closed)

**Comment by piskunow** [comment]
Hi @codebykat ! Thanks for the answer.

> Do you see the popup if you log in on the web at app.simplenote.com as well?
No.

> If not (this confirms that you are successfully verified), can you please try logging out of the app and back in again and let me know if that fixes the issue?
Yes, logging out and in on the system app fixed it.

Thanks!
