### ISSUE TITLE
Shrink whitespace margin inside notes

### ISSUE THREAD

**Issue by rodalpho** [Automattic/simplenote-electron#269]
There’s a huge whitespace margin inside the notes themselves, on the left side. Wasted space there too. Would like the "super condensed" option I requested in a previous issue to shrink this also.

**Comment by drw158** [comment]
Thanks for the feedback. There aren't any plans to adjust the whitespace in the editor itself, but we are looking at an option to resize the note list. We have a max width on the editor text, because after a certain point, having too many characters on one line is a hinderance for legibility. In the mean time, I suggest adjust the width of the app window. That will decrease the whitespace in the editor.
