### ISSUE TITLE
Memory usage is extreme

### ISSUE THREAD

**Issue by rodalpho** [Automattic/simplenote-electron#270]
On my windows 10 x64 system,

Resophnotes: 15MB
Simplenotes React: 73MB
Evernotes: 43MB (!)

Evernotes is a very, very heavy program exposing a ton of functionality. Using more RAM than Evernotes for a program handling text-only notes should be a concern.

**Comment by dmsnell** [comment]
Ouch! thanks for the report @rodalpho 

As this is a first release, it doesn't surprise me that we have some overhead we don't need (we've been focussing on the functionality). Keep an eye out in the future for optimizations, and feel free to file a PR to fix some yourself if you discover any underlying causes :wink:

**Comment by rodalpho** [comment]
Totally understand it's your first release, just wanted to get this on the list!

**Comment by abirwas** [comment]
That's mostly a problem with Electron I believe. Even just a wrapper for a webpage (using nativefier) can use up close to that amount of memory. I'd be very surprised if they significantly reduced it (not discouraging anyone though). Remember, we've got almost a full chromium running in the backend.

**Comment by dmsnell** [comment]
That's a great point @abirwas. I think it will be great to compare memory usage between accounts with many notes vs. those that are basically empty.

**Comment by abirwas** [comment]
Ok then, on a account with one note, the memory usage is 22 + 21 + 16 = 59 (adding up three the memory usage of 3 processes). This is on Windows 10 64 bit.

**Comment by roundhill** [comment]
Is 73MB of memory `extreme` these days anyways?

**Comment by abirwas** [comment]
@roundhill It is not, usually, but in this case, for a simple note taker, it is a bit too high. That said I am pleasantly surprised that this is actually running on electron and still using such low amount of memory. Despite this I still can't use it though due to functionality problems (that's an issue for another thread).

**Comment by dmsnell** [comment]
@rodalpho I'm going to close this issue not because it's not an issue but because instead it's not going to be something we can do much about for the foreseeable future. as has been pointed out, most of that bloat is coming in through Electron simply being Electron. Unfortunately, it would not have been feasible for us to support out-of-browser applications on Linux and Windows had we not taken advantage of this technology. We'll continue to keep an eye on performance and memory usage and tackle issues as they arise and merit priority above other issues.
