### ISSUE TITLE
Login issue (blocked IP address?)

### ISSUE THREAD

**Issue by djordjeandrejevic** [Automattic/simplenote-electron#2703]
I'm using Simplenote 2.7.0 on Ubuntu 18.04 and I have an issue while trying to login. Debugging console is telling me that _auth.simperium.com_ request has timed out.

I've also tried accessing _simperium.com_ website through a web browser and the result is the same - can't access it.

![2021-03-01_11-38_1](https://user-images.githubusercontent.com/8862464/109486079-b707a200-7a82-11eb-976c-ff51380ab749.png)

When I turn off my router for a while and get a new IP, it gets resolved. So my guess is that my IP address is being automatically blocked on Simperium side for some reason.

It looks to me that issues #2682 and #2699 have the exact same problem.

I've tried sending this to contact@simperium.com, but ended up with "Address not found" reply from mail delivery system.

Could someone take a look, please?

Thanks,
Djordje

**Comment by djordjeandrejevic** [comment]
After bit of research, I think the problem might be caused due to my ISP using [CG-NAT](https://en.wikipedia.org/wiki/Carrier-grade_NAT) for handling IPv4 addresses. Maybe the [free trial of 250K requests](https://simperium.com/pricing/) was exceeded by this "umbrella" IP address that was assigned to me by CG-NAT and that was causing login fails.

Many ISPs (at least in my country) are now using or moving to CG-NAT.

Thus, I don't think the whole _simperium.com_ website should be down because of this, without any notice to us, users. Also, contact@simperium.com email seems to be useless.

In case of Simplenote - more specific error code for this situation would be more helpful instead of generic "Could not log in with the provided email address and password." error.

Or, even better - some sort of (re)captcha in these situations would probably help. For instance, Deezer electron app uses these.

Note that these are just my assumptions, I would love to hear someone else's thought on this.

**Comment by codebykat** [comment]
Hi @djordjeandrejevic, thanks for getting in touch. Can you please reach out to us at contact@simplenote.com so we can investigate further?

Also, where did you find the contact@simperium.com address? ~It's old, however... I think it probably does get into our system, but it might not be getting tagged appropriately to come to our attention right away.~ [Edited: It SHOULD still be going into our system, I see now you said it bounced.] I'd like to look into that more.

I'm closing this issue because we can't debug account-related issues on the public GitHub. :)

**Comment by seltzered** [comment]
Noticing this issue as well, was having trouble syncing files for a few weeks so logged out of the linux app and now can't login at all, though website works fine.

A workaround for those encountering this might be to just log into the simplenote website in Chrome and 'install' it [as an app](https://support.google.com/chrome_webstore/answer/3060053?hl=en), or do [Desktop Shortcut](https://support.mozilla.org/en-US/kb/create-desktop-shortcut-website) on Firefox.

**Comment by codebykat** [comment]
Hi @seltzered or others with this issue, an inability to sync via the app might indicate a misconfiguration of your account on the backend, which we are able to fix on a case-by-case basis. This repository is a great place to report issues with the code, but not so much for account issues, since we need to know your email address to look into it. Please do get in touch with our support folks to help investigate!
