### ISSUE TITLE
Exclude notes from default view by tag name

### ISSUE THREAD

**Issue by Symbitic** [Automattic/simplenote-electron#2729]
### What

This is a feature request for my pull request, #2701.

Adds 'Hidden tags' to settings. Any note that contains at least one of the tags listed under Hidden tags will not be visible in the default 'All Notes' view. They will still be visible in the tag view.

### Why

Users may want to be able to exclude certain notes from the default All Notes view if they have a large number of notes. This allows specific filtering of notes based on tags.

### How

See my pull request.

**Comment by sandymcfadden** [comment]
Thank you so much for taking the time to submit a PR with your feature request!

We try to be extra diligent about adding new settings and options to keep things as straightforward as we can. At this point in time, this isn't a feature we are looking to add to the app.

Likely best to use the existing tags feature as a workaround to accomplish what you are looking for here. For example, you could add a tag to only the notes you want to show, then click to view the tag instead of the All Notes view.
