### ISSUE TITLE
Add an editor-only view, or fullscreen

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#273]
This would mean hiding the note list or expanding the editor to take up the whole window.

See #443 for some design and discussion on how to do this.

**Comment by skandl** [comment]
Hi, is this something you would accept an implementation in a PR? I'm personally more interested in a "distraction-free" or "zen" view mode, and am curious if implemented it would be considered for inclusion in the app?

**Comment by dmsnell** [comment]
absolutely @skandl! and if you need some help figuring out how to get started contributing please don't hesitate to ask

if you start working on actual code though I would like to encourage you to be very communicative up-front here because we'll want to partner together on things like design choices and technical patterns.

❤️

**Comment by drw158** [comment]
I just updated the issue with some history, and also added it to the FAQ

@roundhill I believe we talked a bit about this recently. Do you remember if we landed on a good solution?

**Comment by roundhill** [comment]
> Do you remember if we landed on a good solution?

I think we decided to not do a button (we're running out of space), but instead put this as a 'Editor only' option in the `View` menu.

**Comment by roundhill** [comment]
And a keyboard shortcut for it would be awesome 👍

**Comment by mirka** [comment]
Closed in favor of #796
