### ISSUE TITLE
config.js and it's security unexplained for building public builds.

### ISSUE THREAD

**Issue by envygeeks** [Automattic/simplenote-electron#280]
Please provide valid steps for how you actually build this package for Linux.  You explain in it's basic form "config.js" in the `lib/` folder but you do not explain this in the slightest when it comes to building at all and whether we need those keys (and if there is a security concern.)

**Comment by dmsnell** [comment]
@envygeeks for now we're not publishing instructions for building this so that it connects to the actual Simplenote servers, but we're working on moving in that direction. It's also possible to build this to point at a local Simperium server, such as can be powered with https://github.com/simperium/node-simperium.

building for the linux binary should be able to be accomplished with `make package-linux`

**Comment by dmsnell** [comment]
This should no longer be a challenge since the merge of #574!
