### ISSUE TITLE
Tabs don't align properly

### ISSUE THREAD

**Issue by dimitry-ishenko** [Automattic/simplenote-electron#2832]
Trying to enter text in few columns and align them using the TAB key and I get this:

![Screenshot from 2021-04-08 10-40-35](https://user-images.githubusercontent.com/2858291/114065631-df947000-9868-11eb-8848-c84374039efc.png)

![Screenshot from 2021-04-08 10-41-20](https://user-images.githubusercontent.com/2858291/114065647-e28f6080-9868-11eb-8dee-537a6c89075b.png)

This used to work in an older version of the app. I've recently upgraded to 2.8.0 and today to 2.9.0. Both version are broken.

Please also note, in the first image the app seems to insert the tab char and in the 2nd spaces. The first note was created with the earlier version of the app. And the 2nd is a new test note I've created.

### Expected

The columns separated by tabs should align.

### Observed

The columns separated by tabs don't align.

### Reproduced

1. Create new note.
2. Enter stuff, press the TAB key one or more times, enter more stuff, press the ENTER key.
3. Rinse and repeat.
4. Observe misalignment of the columns.

### Where did you see the bug

- System Make: Dell
- System Model: XPS 13 9300
- OS: Ubuntu Linux
- OS version: 20.10
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.8.0 and 2.9.0

**Comment by dimitry-ishenko** [comment]
Confirmed today that the last working version where tabs align properly is 1.21.1. All 2.x.x versions starting with 2.0.0 are broken.

**Comment by codebykat** [comment]
Hi @dimitry-ishenko, we recommend using Markdown tables to align columns of text, because tab alignment has exactly this sort of problem (especially if notes are edited on multiple platforms).

The change from 1.x -> 2.x version involved a complete replacement of our editor component, so it's not really a surprise that the way tabs are rendered has changed.

Interestingly, if you were to paste in some content with tabs, it might actually work, as the underlying editor settings default to "detect indentation from the document", and we haven't set them one way or the other. https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.iglobaleditoroptions.html#detectindentation

Here's a link to more info about the table syntax in Markdown, which should allow you to align things consistently across versions and platforms: https://github.github.com/gfm/#tables-extension-

See also: #619

**Comment by dimitry-ishenko** [comment]
@codebykat yes I am fully aware of the markdown tables. However, I have notes that I edit all the time and I need them to not only look pretty in preview mode, I need the columns to line up in edit mode when I'm trying to edit the data.

With 1.x I could simply go to the text I need to change and do so:

<img src=https://user-images.githubusercontent.com/2858291/114897262-10335700-9ddf-11eb-941b-2f66cc886d48.gif width=50%></img>

With your suggested "workaround" I not only have to constantly switch between preview and edit modes, but as soon as I switch to the edit mode, the table collapses into an unreadable blob of numbers:

<img src=https://user-images.githubusercontent.com/2858291/114897623-6b654980-9ddf-11eb-972c-fac9459c5a3a.gif width=50%></img>

And this is just a simplified example (my real tables have more columns).

Perhaps someone at Microsoft doesn't know why the TAB key exists? From [the wikipedia article](https://en.wikipedia.org/wiki/Tab_key): **The word tab derives from the word tabulate, which means "to arrange data in a tabular, or table, form."**

This wouldn't be the first time for them:

<img src="https://www.cnet.com/a/img/FHt7PVnr7QoYP1eQdy80L9Jd9Ug=/1200x675/2012/09/18/4604f8db-bb76-11e2-8a8e-0291187978f3/NDA_Microsoft_Sculpt_Comfort_Keyboard_35454626_ovr01.jpg"></img>

(Notice the missing INSERT key.)

IMHO being able to align columns with the TAB key is an essential functionality and I can't think of any other respectful editor that doesn't have it. Please consider re-opening the issue.
