### ISSUE TITLE
Using in-browser spell checking on web app

### ISSUE THREAD

**Issue by chromer030** [Automattic/simplenote-electron#2927]
### What

Using the capability of spell checking in web browser (chrome for example)
### Why

On web app It would be great if Simple Note could use browser spell checking, this will improve user experience , lots of users use Web app instead of Desktop client , users of Chrome OS , BSD users , etc.

**Comment by pachlava** [comment]
Thank you for the report @chromer030. Unfortunately, at the moment the spell checkers built into browsers have no access to the editor content because of the technical limitation: the editor in Simplenote Web/Electron is based on [Monaco editor](https://github.com/microsoft/monaco-editor/issues/1977).

We have #2410 where we track similar requests, I have just added you comment there and linked this issue. We hope to solve the issue in the future.
