### ISSUE TITLE
Can't login in local development environment

### ISSUE THREAD

**Issue by ErnieBernie10** [Automattic/simplenote-electron#2931]
### Expected

Can login to account.

### Observed

Cannot login to account.

### Reproduced

1. Sign up for a new account inside the dev env.
2. Verify email address
3. Login to account on dev env
4. I get message that credentials are invalid. Yes I am sure my credentials are correct. I've tried with two separate accounts already. Tried resetting my password multiple times as well.

![image](https://user-images.githubusercontent.com/30663198/121771121-b4324800-cb6d-11eb-8d24-76c56cc69035.png)

### Where did you see the bug

- System Make: make package-linux
- System Model:
- OS:Linux: pop-os 
- OS version: 5.11.0-7614-generic
- Browser (if applicable): Electron
- Browser version (if applicable): Electron
- Simplenote app version: 2.13.0

**Comment by codebykat** [comment]
Hi @ErnieBernie10, this is currently expected unfortunately, as we have not yet updated the development workflow to account for email verification. This is tracked under #2853. Can you tell me more about what you were trying to test or accomplish and maybe we can suggest a workaround?

**Comment by ErnieBernie10** [comment]
I need to get to the note editor. Any way to do that without logging in?

**Comment by codebykat** [comment]
It hasn't been possible to use Simplenote without an account for many many years (and then, only on Android). When you say you need to get to the note editor, are you trying to work on the app itself, or trying to run it? If the latter, is there a reason the downloadable app builds aren't working for you?

**Comment by ErnieBernie10** [comment]
I'm trying to work on it

**Comment by ramons03** [comment]
Hello. If you can't login you need to review the api documentation of simperum to create a new user, i did not see that in the documentation.
The api key is in the config.js file.
https://simperium.com/docs/reference/http/#auth

**Comment by codebykat** [comment]
Hi @ramons03, thanks for providing that link! Were you able to get a local dev environment set up by creating a user directly in the development database? I would be pleasantly surprised if that worked, to be honest, as I was thinking it would still need to contact the backend (which is now hard-coded to the production site). But I haven't tried it.

Unfortunately since we have introduced required email verification to the account creation flow, the development database workflow is pretty broken. We need to come up with a workaround so that other developers can still contribute to the app, but we haven't had the bandwidth for that yet. It is something we to intend to address.

**Comment by ramons03** [comment]
> Were you able to get a local dev environment set up by creating a user directly in the development database?

Yes, i was able to create a user using the api key.
I was able to create notes, but the edit and sync does not work.
