### ISSUE TITLE
Mac App Store version not updated?

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-electron#2933]
The current Mac App Store version of Simplenote says that it's on version 2.13, but was apparently updated 2 weeks ago. This makes no sense as the actual 2.13 updated just dropped a few days ago. It also seems like the MAS version completely skipped 2.12, and perhaps the actual 2.12 update is now incorrectly labeled as 2.13. Screenshot attached.

<img width="1440" alt="Screen Shot 2021-06-17 at 14 45 59" src="https://user-images.githubusercontent.com/45884220/122368500-06fb6d80-cf7b-11eb-9216-01e91adbbe7f.png">

**Comment by ghost** [comment]
My bad. Didn't know it wasn't the electron version being updated on MAS.

**Comment by pachlava** [comment]
Understandable, especially taking into account that both native macOS and Electron are now versioned as 2.13, which is usually not the case. Thanks for reaching out anyway 🙂. And you're right about the fact of 2.12 skip: it was not submitted to MAS since there were no additions, but we kept the internal release wheel turning.

**Comment by ademidun** [comment]
Found this thread because I was wondering the same thing. The version in the mac app store is actually for
https://github.com/Automattic/simplenote-macos

For example, we see here the current version is 2.17 in both [Mac app store](https://apps.apple.com/ca/app/simplenote-notes-and-memos/id692867256?mt=12) and [releases](https://github.com/Automattic/simplenote-macos/releases).

<img width="1171" alt="Screen Shot 2023-01-09 at 7 15 08 AM" src="https://user-images.githubusercontent.com/9806858/211306556-deff981d-c649-405d-8885-986f3b752c46.png">


<img width="1190" alt="Screen Shot 2023-01-09 at 7 19 20 AM" src="https://user-images.githubusercontent.com/9806858/211306561-3d065cf2-8407-45d0-a9c9-f8492ee46dbd.png">
