### ISSUE TITLE
Could not login

### ISSUE THREAD

**Issue by garecanbp** [Automattic/simplenote-electron#2978]
The problem is from my desktop app (version 2.15.0) on Windows 10 failed to synchronize data after 10 hours so I checked the setting and saw the warning Server Connection and CONNECTION_TIME_OUT error in the console so I log out and re-login (after updating the app to 2.16.0) but failed. Then I tried logout on the Android app (ver 2.18) and failed to log in. I am able to log in to web app but could not find my data just empty notes.

### Expected
Successfully log in and find my existing data.

### Observed
The app shows a CONNECTION_TIME_OUT error in the console and The provided email address... error in the desktop and Android app.
Able to log in web app but the data is empty

### Reproduced
Desktop App
1. Log out existing account
2. Input email address & password
3. Click Log in

Android App
1. Log out existing account
2. Click LOG IN
3. Click LOG IN WITH EMAIL
4. Input email address & password
5. Click LOG IN

### Where did you see the bug

Desktop
- System Make: Lenovo
- System Model: T480
- OS: Windows 10 Pro
- OS version: Win 10 version 21H1
- Browser (if applicable): Google Chrome, Microsoft Edge (Chronium)
- Browser version (if applicable): Chrome 92.0.4515.131, Edge  92.0.902.73
- Simplenote app version: 2.15.0 & 2.16.0

Android
- System Make: Xiaomi
- System Model: Redmi Note 9 Pro
- OS: Android 11 (MIUI Global 12.0.1 Stable)
- OS version: Android 10 RKQ1.200826.002
- Simplenote app version: 2.18

**Comment by codebykat** [comment]
Hi @garecanbp, thanks for getting in touch. It sounds like there is some difficulty with your connection to the backend server. Can you please try connecting to a different network and see if that allows you to log in and view your notes?

If not, please drop us a line at support@simplenote.com so we can debug further. I'm closing this issue since it is very difficult for us to debug account-related issues on the public GitHub, but if you email us so we can get more information, we should be able to get to the bottom of it! Thanks!
