### ISSUE TITLE
Unordered List not rendered in Publish Link

### ISSUE THREAD

**Issue by manish-pritmani** [Automattic/simplenote-electron#2985]
Unordered list with these tags is rendered in preview mode in windows application (Simple Note v2.17.0), but it's not getting rendered in the publish link website.

" + This is unordered list "
" - This is unordered list "

**Comment by codebykat** [comment]
Thanks for this report, @manish-pritmani . I wasn't able to reproduce this. My test note looks like this:

<img width="180" alt="Screen Shot 2021-09-02 at 9 21 36 AM" src="https://user-images.githubusercontent.com/52152/131851143-4e254106-66fd-4364-9a20-7d21d4fc02a7.png">

And here's how it looks when published:

<img width="235" alt="Screen Shot 2021-09-02 at 9 21 41 AM" src="https://user-images.githubusercontent.com/52152/131851178-36fe9794-ca23-48a0-af5f-d60dd2aa5dd7.png">

Can you double-check that you have Markdown enabled on the note? Also, is it possible you weren't seeing the most recent version of the published note? You can try clearing the cache on your browser and doing a full reload.

If you're still having this problem, can you please create a test note with the content that isn't working when published, and share the link so that we can investigate further?

**Comment by manish-pritmani** [comment]
I have installed version 2.18.0-beta1 and this is resolved now. Thanks for the help @codebykat 😍
