### ISSUE TITLE
Checkbox is not checked/unchecked by clicking it on mobile web browser

### ISSUE THREAD

**Issue by tiagomar** [Automattic/simplenote-electron#2987]
### Expected
Checkbox should be marked as checked by clicking it.

### Observed
Checkbox is not checked/unchecked by clicking it on mobile web browser 

### Reproduced
1. Open https://develop.simplenote.com/ in Chrome (Android)
2. Create a note with checklist items
3. Try to interact with the checkboxes by clicking them
4. Notice that is not possible to check/uncheck them

https://user-images.githubusercontent.com/42008628/131951125-efb25179-24bb-4bf7-9453-2532ca6d03fe.mp4

### Where did you see the bug
- System Make: n/a
- System Model: n/a
- OS: Android
- OS version: 11
- Browser (if applicable): Google Chrome
- Browser version (if applicable): 92.0.4515.159
- Simplenote app version:  n/a

**Comment by pachlava** [comment]
Thank you for the report @tiagomar !

In Simplenote Electron/Web we use a third-party editor for editing notes, which is [Monaco Editor](https://microsoft.github.io/monaco-editor/#:~:text=The%20Monaco%20editor%20is%20not,browsers%20or%20mobile%20web%20frameworks.). It is not supported on mobile devices. I'm closing the issue because of this 🙂
