### ISSUE TITLE
Tag exist but no notes attach to it (Re-index feature would be great)

### ISSUE THREAD

**Issue by jadupl2** [Automattic/simplenote-electron#3004]
I've been using SimpleNote since the beginning on all my platform (Linux, Windows, MacOS Raspbian, IOS) and I love your product. I often ran into tag that are not attached to any notes. 
I know you have an option for "Untagged Notes", would be great if we could also have an option like "Orphan Tag" that would list all tag without any notes attach to it. Or to have an option to re-index the "tag" (Delete all tag, then read all notes while recreating the tags) . 
I am running the latest version at this time 2.18.0 and I have seen the same problem of all platform.

Thank You for reading me,

**Comment by pachlava** [comment]
This is a nice proposal @jadupl2 ! In fact, we have an internal tracker for feature requests, with already existing 3 similar requests, making it four in total with your request, that I've just added. I'll close the current issue because of that. It's on our development team radar, but we can't predict when exactly will this be implemented.

One thing that might help you at the moment, is that [Android](https://github.com/Automattic/simplenote-android/releases) version provides this information in `Edit Tags` screen:

![Screenshot_20210914-184508_Simplenote](https://user-images.githubusercontent.com/73365754/133290323-4a48fc3d-2937-4d6b-86bc-93fc53f76648.jpg)

I hope this helps meanwhile.

**Comment by jadupl2** [comment]
Thank You for your response, it is appreciated.
