### ISSUE TITLE
Is Simplenote still in active development?

### ISSUE THREAD

**Issue by xmha97** [Automattic/simplenote-electron#3080]
I haven’t seen updates in a few months so just seeing if I should switch apps
https://www.reddit.com/r/Simplenote/comments/t1zv5c/is_simplenote_still_in_active_development/

**Comment by codebykat** [comment]
Hi @xmha97, Simplenote is not going anywhere! We are being kept busy with other projects at the moment but we are still supporting the app, keeping an eye on things and planning for future updates.

Simplenote recently had a period of very active development as we were lucky enough to get to spend quite a bit of time fixing things up and adding new features, but at the moment our development efforts are needed more urgently elsewhere. This isn't the first time that's happened in Simplenote's history and likely won't be the last. Since Simplenote is run by Automattic, we have a number of other apps and projects in our wheelhouse, and have to decide where to focus our work.

But rest assured that we ❤ Simplenote (many of us use it on a daily basis) and do not plan to abandon it!
