### ISSUE TITLE
Email Verification Link Issue

### ISSUE THREAD

**Issue by noor-codes** [Automattic/simplenote-electron#3089]
### Sometimes when we install SimpleNote App on the Desktop, It requires Email Authentication.

The main issue is that the link often ends with one `=` or `==` sign which is often ignored by a web browser or the email client. In my case, it's `Mailspring`

This should be a fix on the server so I won't list further details.
Here's the screenshot for more context. 

![image](https://user-images.githubusercontent.com/28804764/164967304-4ff191d4-8060-4d22-bb03-5f6765243497.png)

Thanks

**Comment by azollafox** [comment]
This was noted by several people on the forum. The log out/back in process doesn't seem to resolve
https://forums.simplenote.com/forums/topic/repeatedly-asking-to-confirm-email-address/#post-304

Simplenote 2.21.0 on Windows 10 Professional on a Lenovo
Yoga 2 laptop
Dell Inspiron (64-bit) with current Windows 10 updates

**Comment by codebykat** [comment]
@azollafox This issue is specifically that the generated links sometimes contain characters that cause them to not work in some email programs. In the case reported here, copy and pasting the link would work (though it is something we should address eventually).

Looking at the forum, it seems that upgrading to the latest version of the app resolved the issue with repeated email verification popups. If others are still having trouble they can contact us from the email address on their account and we can verify on their end.

**Comment by noor-codes** [comment]
I am a web developer so I don't mind, but for the general public that would be confusing.

Thanks for the reply
