### ISSUE TITLE
Simplenote spellcheck not working

### ISSUE THREAD

**Issue by imsamss** [Automattic/simplenote-electron#3101]
Please name the genius behind removing Simplenote's spell check feature.
We are writing here, not drawing. Seeking an alternative note app which has simple and most needed features. It's like simplenote becomes a hardnote. Please help.

**Comment by codebykat** [comment]
Hi, sorry for the trouble. We hope to be able to restore it in the future, but it's unfortunately technically complex because apps that run inside the browser do not have access to the OS-level spell checker, for security reasons. The mobile apps do include spellchecking, as does the desktop app for OSX. This is tracked in #2410 so I'm closing this as a duplicate.

Hopefully our embedded editor, Monaco, will at some point be able to add support for this.
