### ISSUE TITLE
Share Notes with Search Option -> Share All Notes or Sub-Notes Option or Folder Option

### ISSUE THREAD

**Issue by passionate2023** [Automattic/simplenote-electron#3141]
Hi,

Need to share the entire notes as public URLs where no-one should be able to edit/update/delete any of the content. The public sharing URL will be completely READ-ONLY.

I'm able to share a single notes but need to share all notes with search option.

also folder -> notes inside the folder -> share public is not available. 

Thanks

**Comment by codebykat** [comment]
Thanks for the suggestion. Published notes are read-only already (use the Publish rather than Collaborate functionality). We're not planning to add a multi-note publishing workflow at this time. As a workaround, you can use internal note links to create a table of contents that links out to other published notes.
