### ISSUE TITLE
Unable to sign up on simplenote development env

### ISSUE THREAD

**Issue by bruteF04C3** [Automattic/simplenote-electron#3165]
### Expected
I should be able to create an account on simplenote dev

### Observed
Not able to create an account, not receiving an email on the specified email address

### Reproduced
1. Run both node-simperium and simplenote-electron apps
2. Click on "Sign up"
3. Enter email address and submit

### Where did you see the bug
- System Make: Lenovo 
- System Model: ThinkPad L14 Gen 2
- OS: Ubuntu 
- OS version: 22.04.1 LTS
- Browser (if applicable): Google Chrome
- Browser version (if applicable): 108
- Simplenote app version: 2.21.0

**Comment by bruteF04C3** [comment]
Continuing from above,
I think I need an account on "simperium" beforehand but I don't really see any option to register on that platform.
Thanks in advance for any insights :)

**Comment by codebykat** [comment]
We aren't currently creating new developer accounts, sorry for the inconvenience. The development environment needs a complete overhaul and hasn't been working since we upgraded our account process to require email verification. It probably won't be fixed anytime soon. I believe you may be able to point it to the production Simperium backend and use your existing Simplenote account, but this is not something we're able to support at the moment. If you search other issues, there may be workarounds you can try.

**Comment by bruteF04C3** [comment]
Thought so. 
As for using the production creds, I tried that right before searching for a way to use the "dev" environment, could not get past the authentication flow. I might try that again once possible. 

Anyway, thanks for the heads up :)
