### ISSUE TITLE
Integration/Sync of/with local used text-editor

### ISSUE THREAD

**Issue by 0nvx52lt** [Automattic/simplenote-electron#3168]
I thought a feature would be great where one can use the local text-editor (for example I use Kate on Linux) as an implemented editor. It would be great (if this even possible/do-able?) because I (and probably a lot of other people too) could then melt their code and notes together easily and it would be great for usability. I hope what I said is understandable, I'm sadly not the best descriptor - if it's too poorly explained or you need more info on my feature request simply ask me in comments and if the FR is already asked for please link it or delete this post.
### Why

Because it would be great for usability, users would not have to switch between their local text editor and the simplenote-app anymore and it would add more complexity (but some nerds like me like that :])
### How

![2023-10-24_22-29](https://github.com/Automattic/simplenote-electron/assets/97715989/f4c55027-e3de-4cfd-b11c-4d306d732ebd)

**Comment by codebykat** [comment]
There's a lot of prior discussion about this (going back to at least #271), but the short version is that there are many excellent text editors out there which allow you to edit files on the file system, and Simplenote is not likely to become one of them anytime soon. Our priorities for the project are to keep notes in sync to our system and to all your devices. You can always export all of your notes from Simplenote to local text files. However, a constant two-way sync with the filesystem, as you noted, would introduce a lot of complexity and we're not willing to go down that route at this time.

As a fellow nerd, I do appreciate the appeal of complexity, but our guiding principle for Simplenote is to stay true to its mandate of simplicity! Otherwise we would have to rename it Complexnote.

Thank you for getting in touch with this request, even though it's not something we can pursue. Over the years we have looked at this sort of feedback when deciding what direction to take the product and which new features to add.
