### ISSUE TITLE
Hash titles don't render

### ISSUE THREAD

**Issue by mlda065** [Automattic/simplenote-electron#320]
#### Steps to reproduce

Enter the following note

    #Here is a top level title
    
    Alternative top level syntax
    ================

    ##Second level title

    Alternate Second Level syntax
    -------------------------

    body text

#### What I expected

I expect what happens in the web app, which is

![web app](https://cloud.githubusercontent.com/assets/7035647/15849122/45b206f0-2cd4-11e6-90d4-6b9b9de86ae7.png)

#### What happened instead

![Linux](https://cloud.githubusercontent.com/assets/7035647/15849132/578c72c0-2cd4-11e6-8c29-d339a85c23d4.png)

#### OS version

Linux Mint 17.3, Rosa

#### Other

I'm not too familiar with the different flavours of markdown. But the hash notation is in the Daring Fireball version. And since it works in the web app, it should work in the linux app. (From a user's perspective I mean. I have no idea how it's implemented.)

**Comment by drw158** [comment]
The Linux and Windows apps use a slightly different Markdown library. For these apps, you have to put a space after the hash character. This should work for you:

`# Here is a top level title`

The web app does not require the space after the hash character. We consider the Linux/Windows app to be the correct version, since it follows the Daring Fireball syntax more closely.

https://daringfireball.net/projects/markdown/syntax#header
