### ISSUE TITLE
Please consider removing captcha codes and consider using time outs

### ISSUE THREAD

**Issue by Raj2032** [Automattic/simplenote-electron#3227]
Very annoying I am often using private window on public computers and it is annoying that I have to do this recaptcha code everytime I want to log in. Recaptchas are very bad, even if you select the item sometimes it thinks that you got it wrong and asks you to do it over and over again, very frustrating and it is gotten so annoying that I am considering moving to another note application.

If you want to protect from bruit force attack why not lock the user out for 2 minutes after 3 failed attempts (which can also be disabled in settings).

I am not super concerned if somebody hacked my account and deleted my notes as I don't keep personal stuff, as well as it is not end-to-end encrypted so keeping your personal stuff on it would be a bad idea.

**Comment by codebykat** [comment]
Thanks for the feedback, @Raj2032. We've recently adjusted some of the captcha settings to be more forgiving, and there are some changes in the works that should help streamline the login process. We were unfortunately getting a lot of bot traffic so we had to go a bit nuclear as a temporary measure, but I am definitely with you on the captcha being super annoying (I just had to do one four times because apparently I can't identify stairs or something, starting to think I may be a robot after all 🙃).

You're totally correct that the lack of encryption means folks shouldn't be keeping sensitive data in their notes, but not everyone is quite so savvy, so we have to strike a balance as best we can.

**Comment by Raj2032** [comment]
@codebykat Thanks for your response I do hope to see it removed in the near future. Why not have captcha codes done when signing up for accounts to prevent bot attacks?

**Comment by codebykat** [comment]
They are done then too :)

We now have a way to login directly via email which does not require a captcha, so closing this as completed, but please let us know if you have any other thoughts about this!

**Comment by Raj2032** [comment]
Even better I moved to Proton docs already since I don't want to log in multiple times on private browser.
