### ISSUE TITLE
How to uninstall gconf2

### ISSUE THREAD

**Issue by 12elotro** [Automattic/simplenote-electron#3258]
Hi, I have Linux Mint 22 and for it to work SimpleNote I had to install gconf2 dependency 

 ```
sudo dpkg -i gconf2-common_3.2.6-8_all.deb
sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb 
sudo dpkg -i libldap-2.5-0_2.5.13+dfsg-5_amd64.deb
sudo dpkg -i gconf-service_3.2.6-8_amd64.deb
sudo dpkg -i gconf2_3.2.6-8_amd64.deb

```
Now I want to uninstall this dependency, do I just check them and uninstall them with synaptic? Or is there something I need to do? Is there any order I need to follow?

Thanks, I'm a newbie.

**Comment by codebykat** [comment]
Hi @12elotro, first off I just want to confirm that you're able to install the new version without the gconf dependency. We removed that dependency in the upcoming 2.22.2 version. It's currently in beta and can be downloaded here: https://github.com/Automattic/simplenote-electron/releases/tag/v2.22.2-beta.5

To uninstall any package installed with `dpkg -i`, you can use the `-r` option instead (for remove). So it would be something like `sudo dpkg -r gconf2_3.2.6-8_amd64.deb`. The order shouldn't matter, but if `dpkg` complains that it can't uninstall due to dependencies from other packages, you can uninstall those packages first.

**Comment by 12elotro** [comment]
Thank you very much for the reply. Best regards.
