### ISSUE TITLE
Crypted notes vs. full-text search

### ISSUE THREAD

**Issue by AntonioIT** [Automattic/simplenote-electron#335]
Notes are not crypted to allow full-text search, but it would be useful to choose between fulltext-search an no cryptation OR data crypted with no-fulltext search allowed.
Notes title only should remain in clear.

**Comment by dmsnell** [comment]
@AntonioIT we don't encrypt notes in any of the apps the reason is much deeper than allowing full-text search. In fact, we could still do full-text searches even if the notes were encrypted. It is not likely that we will support any kind of encryption for some time as it would require architectural-level changes. Therefore I'm going to close this issue. Thanks!
