### ISSUE TITLE
Remember cursor position per note

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#42]
If you're working on large notes and are switching back and forth between them, the cursor position seems to just stay at where it was in the previous note.

It'd be handy if we could store the last cursor position for a note and restore it when the note is loaded again.

**Comment by codebykat** [comment]
Monaco actually does this now, so this was implemented ~incidentally~ with a lot of hard and much-appreciated work by @dmsnell in 2.0.

**Comment by dmsnell** [comment]
> Monaco actually does this now

well, we added code to tell Monaco to move its cursor to the last position

> so this was implemented ~incidentally~ in 2.0.

it was an intentional enhancement performed as a result of being able to finally do so with the overhaul of the data/state system. it's not trivial either - it tracks remote updates that modify the note and accordingly moves the cursor position even when the note isn't open 😉

**Comment by codebykat** [comment]
Sorry @dmsnell, my bad. Edited my original remark 😇
