### ISSUE TITLE
Tags: Unable to delete tags using Delete key

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-electron#420]
#### Steps to reproduce
1. Create a note and add some tags to it.
2. Viewing a note, click a tag added to that note and press the Delete key
#### What I expected

That the tag would be deleted from that note.
#### What happened instead

Nothing happened. However, pressing the Backspace key does remove the tag.
#### OS version

Windows 7 Home Premium SP1, 
Simplenote v 1.0.5

**Comment by DorkeyDear** [comment]
I can confirm that this bug still exists in version 1.0.7 of the Windows app.

**Comment by dmsnell** [comment]
Thanks for the update @DorkeyDear - we're about to change the behavior of tag deletion so that it's a single click instead of two. On that note, there wouldn't be a place to hit the delete key.

I'm going to close this for now as a result. This brings up one more use case in my head, however, which I will let @drw158 respond to. If we use the arrow keys from the tag insert area will we still allow selecting the other tags. If that's the case, we should reopen this or make sure we provide for that in the PR that changes the tag behavior.
