### ISSUE TITLE
AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [Automattic/simplenote-electron#422]
* Operating system: Linux
* Simplenote version: Latest

Please provide an [AppImage](http://appimage.org/) for Linux. This will allow Simplenote to run on many Linux distributions at once. `electron-builder` has support for it, so should be really easy.

**Comment by swalladge** [comment]
@probonopd while this would be a nice idea, I also suggest reaching out to package maintainers for the distro you are wanting to run Simplenote on to see if someone will be willing to create distro-specific packages for it (if it doesn't already exist). For example, I am currently maintaining a [pkgbuild on the aur](https://aur.archlinux.org/packages/simplenote-electron-bin/) for easy installation on Archlinux.

**Comment by dmsnell** [comment]
@probonopd that sounds like a great idea. I looked into this a little bit while on a flight yesterday but was limited due to lack of reliable internet. To my knowledge it doesn't look like there is anything to prevent us from doing it. Of course, we might get there faster if someone offers a PR for it :wink:. We'll update here as we learn more and if we put out some code to this end. Thanks for filing the issue and pointing us at AppImage!

@swalladge it's great to hear about awesome work like what you are doing. thanks for making it possible to more easily spread Simplenote ❤️ !

**Comment by probonopd** [comment]
@dmsnell it's so trivially easy that I don't think its worthwhile to do a PR:

1. Edit package.json to use the latest electron-builder.

2. Edit package.json — add after "build": { ... }:

```
    , "linux": {
      "target": ["AppImage"]
    },

```
Then, `npm install` or `npm run dist or npm run dist -- --linux=AppImage` if you want to explicitly set target and do not edit package.json.

**Comment by natanielcz** [comment]
I let myself to take care of this one because it wasn't modified for a year. I didn't create AppImage installer because I think that still there aren't many people using this format. Instead I've added support for RPM. @probonopd if you think that I'm wrong and there is a lot of people using AppImage and FlatPak I can take care of this two installers too. 

I'd be grateful If someone could test changes from my recent PR because I don't have RPM based distro.

**Comment by swalladge** [comment]
@natanielcz btw it doesn't matter how many people use the appimage format, because it's simply an executable file with no dependencies. Others like snap and (afaik) flatpak require installing a manager software first though.

**Comment by probonopd** [comment]
Since AppImage is the default format for electron-builder Linux builds, I see lots of usage especially for Electron-based apps. Due to the good support in electron-builder I expect this to be straightforward but in any case let me know if you need support @natanielcz.

**Comment by natanielcz** [comment]
Ok. I'll try to create AppImage. It's something new for me because this is the first electron app I participate but I'll do my best ;)

**Comment by natanielcz** [comment]
I've updated my pull request. We are able to build rpm, deb, AppImage and tar.gz packages. There are two new dependencies on Linux: icnsutils and graphicsmagick.
I've also updated Makefile. Linux installers are put into directory /release. If it should be other location just tell me.

**Comment by jotak** [comment]
I can't see an RPM distribution in github's releases, is there extra steps to get it?
