### ISSUE TITLE
F11 is not the best choice for full screen toggle

### ISSUE THREAD

**Issue by rcarmo** [Automattic/simplenote-electron#455]
#### Steps to reproduce
1. Launch SImplenote on a machine with only 10 function keys (Like an Acer C720)
2. Toggle fullscreen
3. Try to revert back to regular mode

#### What I expected

Some way to get out of full screen mode

#### What happened instead

I was stuck and had to kill the app to exit

#### OS version

Linux, Ubuntu 16.04 LTS

**Comment by dmsnell** [comment]
Thanks for reporting @rcarmo. We can look into this but I'm not sure if we'll switch away from <kbd>F11</kbd> because it's pretty standard. That's very unfortunate that your laptop has no <kbd>F11</kbd>. In a quick search online I found that others with that model laptop have remapped several keys so that they can access common keystrokes and shortcuts.

**Comment by rcarmo** [comment]
Yeah, well, it's still not ideal when there's no other way to toggle fullscreen.

**Comment by Ajkula91** [comment]
Yeah, I can imagine some members of my family destroying computer because there is no "X" button somewhere in the app, they could get stuck because they don't know about "F11"

**Comment by troypdx** [comment]
I was able to exit full screen under Ubuntu 18.04 by pressing Alt+V then choose the View > Toggle Fullscreen Mode menu item.
