### ISSUE TITLE
Status bar to show sync / autosave status (feature request)

### ISSUE THREAD

**Issue by nagpai** [Automattic/simplenote-electron#459]
It will be helpful if we have a status bar or a message that shows if a note has been successfully synced or saved in a system.

**Comment by dmsnell** [comment]
For a quick summary around this issue I'd like to summarize what _is_ and _isn't_ possible surrounding a visual indicator. It's _possible_ to indicate that we have local changes which we haven't yet pushed out to Simperium. It's _possible_ to know that after a successful response from the server that our local changes have been accepted and if we have no further local changes since that confirmation we can turn off the indicator. It's _impossible_ to know if we have "fully sync'ed" because the fundamental working model of Simperium (which powers Simplenote) is that the app is _always_ in a constant process of synchronizing. We cannot know locally if there are new changes on the server on their way to our copy of the app. We also cannot know if the server successfully folds in our changes if we get no response.

This means that we can know for sure if we haven't _attempted_ to synchronize changes and we can know if our changes were accepted but we _cannot_ know if our changes fail to synchronize and we cannot know for sure that they succeeded or failed unless we hear back from the server.

That all being said we have been stewing on this issue and hope to have some solution worked out at some point, but probably not before 1.0.9 is done.

Thanks for the feedback, many others have asked about a similar feature.

**Comment by unforgettableid** [comment]
> We cannot know locally if there are new changes on the server on their way to our copy of the app.

But, if the server tells the client that there are no new changes available on the server, surely the client app can now report something like this:

"Last sync attempt finished: Apr. 21, 9:15:34 AM"
"Last sync status: Sync completed successfully."

Am I correct?

**Comment by unforgettableid** [comment]
Related: #544: "Please add a new 'File > Sync and Exit' menu command"

**Comment by dmsnell** [comment]
> But, if the server tells the client that there are no new changes available on the server, surely the client app can now report something like this:
> 
> "Last sync attempt finished: Apr. 21, 9:15:34 AM"
> "Last sync status: Sync completed successfully."
> 
> Am I correct?

@unforgettableid I'll try not to be too redundant here since I started answering in your other issue.

Simplenote never "attempts a sync" per se. When it has local changes it pushes those out to the server. When the server receives updates it sends those updates out to the apps. Since a stateful socket between the server and apps is maintained whenever they are open these updates are unsolicited meaning that the app never asks the server for recent updates; the server simply sends them as they come. Since Simplenote is by nature a distributed application and updates to the same note could happen from different devices at near the same time we also run into race conditions with the updates, meaning that an announcement from the server could be on its way at the time we think we are up to date (meaning that we are now no longer up to date but don't realize it).

Now, we can ask ourselves at any given point in time when we aren't receiving an update notice from the server: did we not receive an update notice because we are up to date with the information or did we fail to receive the network packets?

**Comment by dmsnell** [comment]
@roundhill adding some random notes here after digging in:

I believe that we could hook into `node-simperium` for a few more helpful bits but it's going to take some time and probably way lower priority than fixing the darn bug in #602 

`node-simperium` tracks changes that are in-flight and also ones that are queued to ship off. @beaucollins can probably correct me if I'm wrong but it looks like it does things one at a time and waits for a response from the server before sending out the next change.

many aspects of our local queueing are still mysterious to me but I think we could end up with lists of notes and even specific parts of notes that fall into these categories

 - changes which have been made locally and definitely haven't been synchronized
 - changes which have been made locally and definitely _have_ been synchronized
 - changes which have been made locally and may or may not have been synchronized

some kind of network spinner could be a great implementation detail for visualizing the third kind in that list. having definitely-unsynchronized edits is a good reason to confirm before closing too.

**Comment by msilbers** [comment]
This feature is still requested often, most recently in #1388662-zen
