### ISSUE TITLE
Split view when Markdown is enabled

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [Automattic/simplenote-electron#460]
When editing Markdown notes, I'd like to have a split view where on one side I'd have the text and on the other side I'd have the Markdown result.

**Comment by dmsnell** [comment]
Hi @RicardoEPRodrigues - thanks for submitting this issue here. I know that we have no immediate plans to add a split view, even though I too enjoy them when working in Markdown. Before we would likely do this, if we were to add it, we would probably also want to have it working in the mobile apps.

cc: @drw158

**Comment by Novbert** [comment]
Although I think introducing split view would unnecessarily overcomplicate simplenote, I think it would be useful if the Edit view and Markdown view could be synchronized, so that I can see the same part of text when switching between the two. When working on longer texts it is a bit of a hassle that I always need to find the place I want to edit, when I switch between the two views.

**Comment by RicardoEPRodrigues** [comment]
I see your point of view, Simplenote should be Simple, but the current tab switching it's a little annoying to me, maybe the solution is somewhere in between.

**Comment by yonathanF** [comment]
I am interested in this feature too. Maybe updating line by line could work? When I press enter, the line I just wrote could be converted. Or have an "update" button so everything I have so far will get converted (like pressing compile in Tex editors).

**Comment by hfactor** [comment]
The current tab switch is not a good way. So does having a split. Split will reduce the editor space. I think preview for markdown should be there by default in editor itself (like Bear Writer)

**Comment by mizejewski** [comment]
The swipe back and forth to preview markdown works well for the mobile format, but on a larger screen I would really prefer side by side markdown/preview panes. The current button clicking to switch between then is *really* annoying.

**Comment by mizejewski** [comment]
Just looked at [Bear](http://www.bear-writer.com/) after it was mentioned above by @hfactor. I agree that this merged option could work well too. It's actually pretty awesome in its simplicity and clarity.

**Comment by drw158** [comment]
I believe #418 would fix this issue once it is merged. It formats Markdown in the editor. We don't have a lot of time to work on it, but it should come eventually.

**Comment by dmsnell** [comment]
#418 is more of an experiment than anything else but I'd like to get it in. I agree that Atom, Bear, MacDown, and DayOne all have great Markdown editing experiences. The thing that #418 doesn't address is block contexts such as code fencing, but that shouldn't be a big problem as the blocks are relatively easy to identify.

@drw158 do we have any fundamental issues with a split view on wide screens?

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
