### ISSUE TITLE
Linux desktop editing followed by web/mobile editing causes sync issues

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/simplenote-electron#482]
Reported by a user in #2985537-t and confirmed by two others as well. Since I haven't been able to reproduce it myself here's the user's own words on how the issue happens:

1. Open the desktop app and enter some text

2. Leaving the desktop app open, go to the webapp or the android app. Enter some text. After a moment, the text vanishes from the web or android app.

3. ... The text appears on the android app. 

@vindl said:

> I was able to reproduce this on Ubuntu 16.04. The text disappears from Android app as described in step 2, and immediately after that it shows up in the desktop app (at this point it seems to be diverging from what's described in step 3, but it's still buggy)...what's interesting is that this doesn't seem to occur for notes created with Android app, but only for the ones that I've created using the desktop app

@roundhill said:

> I can reproduce that using iOS too, so I think it's probably a bug with the electron app when it receives changes for an open note

**Comment by KokkieH** [comment]
See post titled "Windows sync in 1.0.7-beta" on internal p2. I think it might be the same issue.

**Comment by Hywan** [comment]
Apparently we have another issue of the same kind in #3128722-T. It implies Linux, Android, and the web version.

**Comment by dmsnell** [comment]
I believe that this is directly related to the bug causing the issues in #602 and so I'm going to close this ticket as a duplicate. it's not because it isn't important but rather for our own organization and to try to keep the related issues together. I spend shamefully too much time this weekend auditing these failures and have gained some insight into the problem - thanks again for everyone who has taken the time to report and interact here. you are invited to join the part in #602 unless you believe strongly that these two are separate.
