### ISSUE TITLE
Add menu item to open the Simplenote window

### ISSUE THREAD

**Issue by davewhitley** [Automattic/simplenote-electron#496]
Apparently, it's against standards to not have a menu item to open the app's window. Meaning, once you close the app window, there's not an explicit menu item under Window to open it. You have to click on the icon in the dock to open the window.

This was brought up in the native Mac app: https://github.com/Automattic/simplenote-macos/issues/111

I suggest we add a new menu item under Window named "Simplenote App" with no shortcut.

Of course, this is only relevant if we publish to the App Store.

**Comment by belcherj** [comment]
Closing as we now have a macOS native app.

**Comment by codebykat** [comment]
If I'm reading this right it is something we fixed in the native app that we should consider fixing in the Electron app as well?

I just tested in Electron and this looks to still be an issue. If you close the window with Cmd+W there is no way to get it back without closing the app, not even New Note.

**Comment by belcherj** [comment]
We do not officially support the OSX app for electron and only provide it as a convenience. If this is a quick change I'm fine with making it but it is an extremely low priority.

**Comment by belcherj** [comment]
You can click it in the dock and reopen. I feel like that is good enough.

**Comment by belcherj** [comment]
Closing as we no longer support macOS Electron. The native app should be used.
