### ISSUE TITLE
Search doesn't find all the notes with search term

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#535]
#### Steps to reproduce
1. Create three notes in the Windows app with the following three lines, one line for each note:

House 10/3/17 Shane
House notes 18/3/17
House Visit 04/03/17

2. Try searching for "house". Only the first and last note is found. Simplenote doesn't find the second note.

I tested this in the Mac electron app and can reproduce.

Related: https://github.com/Automattic/simplenote-electron/issues/333

**Comment by gie3d** [comment]
I did some investigation into this issue and found this might be root cause.

in **lib/utils/filter-notes.js**, the logic to find related notes are using.
```javascript
return notes
               .filter( overEvery( [
                   matchesTrashView( showTrash ),
                   matchesTag( tag ),
                   matchesSearch( new RegExp( escapeRegExp( filter ), 'gi' ) ),
] ) );
```

the interesting part is in **matchesSearch** which uses 'gi' (g - global). It then calls to includesSearch

```javascript
const includesSearch = ( text, search ) => search.test( text || '' );
```

and the problem is search.test() which uses RegEx 'gi'. When it finds a match, it sets search.lastIndex to that string position. When it comes to the next note, it won't start examining at the beginning of it but it will start at the lastIndex. ([http://stackoverflow.com/questions/1520800/why-regexp-with-global-flag-in-javascript-give-wrong-results](http://stackoverflow.com/questions/1520800/why-regexp-with-global-flag-in-javascript-give-wrong-results))

So I think the solution is to reset the search.lastIndex = 0; every time it comes to this function

```javascript
const includesSearch = ( text, search ) => {
	search.lastIndex = 0;
	return search.test( text || '' );
}
```

Would this fix is acceptable and could I submit a pull request?
