### ISSUE TITLE
Tabs stripped from published note

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/simplenote-electron#537]
I'm not quite sure if this is by design or indeed a bug. It was raised by a user in 3096496-t. If you create a note with indents, the indents will be stripped from the note when it's published online.

#### Steps to reproduce
1. Start a new note.
2. Title it "Testing." Then, within the body of the note, enter some lines of text using tabs to indent them.
3. Publish the note.

#### What I expected
The indents to remain

#### What happened instead
The indents throughout the note were removed.

#### OS version
Sierra. This also seems to happen on the web and iPhone app.

#### Screenshot / Video
<img width="594" alt="screen shot 2017-04-01 at 4 58 10 pm" src="https://cloud.githubusercontent.com/assets/7240478/24583080/9fe07158-16fc-11e7-9f14-2f7f3e5e800f.png">
<img width="548" alt="screen shot 2017-04-01 at 4 58 15 pm" src="https://cloud.githubusercontent.com/assets/7240478/24583081/9fe17c06-16fc-11e7-9660-22168bb4230d.png">

**Comment by codebykat** [comment]
I have a fix in the pipeline for this for plain-text notes. In that case I agree that the published note should look like it looks in the editor. However, I'm not sure what we should do for Markdown-enabled notes, since Markdown assigns syntactic meaning to indents (e.g. for nested lists, code blocks, and so on).
