### ISSUE TITLE
History: if there is no history, slider should be disabled

### ISSUE THREAD

**Issue by davewhitley** [Automattic/simplenote-electron#587]
If there is no history on the note, the history slider can be confusing because it looks the same as a note with history.  I tried dragging the slider, but nothing happens.

This note has no history, but it looks like I can slide the slider, and there is no message saying that there is no history:

![screen shot 2017-07-12 at 10 42 53 am](https://user-images.githubusercontent.com/618551/28126447-1f115658-66ef-11e7-8ae3-cfdf9d2cad04.png)

This might only be possible with the first "Welcome" note as shown in the screenshot. Even if you create a new note and copy text into the note, there is still history (the earliest revision being a blank note).

This potentially has a low priority since I can't think of another way a note would have no history.

### Possible solutions if there is no history:

- disable the history clock button
- disable the slider
- Show a message in place of the history date, saying "No history"

### Possible solutions if there is only one revision:

I also found it a little hard to use the slider if there was just one revision (the only revision being an empty note)

I think it would be better if we only enable the history button if there is more than one revision. It would make sense to me, since I don't find it useful to just go back to the empty note state.

**Comment by dmsnell** [comment]
Part of our trouble is that we can only access history when online because we don't pull that in. I think it's reasonable, especially on desktop, to start loading the history in when we open a note (maybe a second or so after having loaded it). That would mean we could disable it when not online completely and also know in advance how many revisions we have. I'll look into this, maybe slate it for 1.0.10 since it will probably require more work.

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
