### ISSUE TITLE
Can't use Markdown headers on Mac

### ISSUE THREAD

**Issue by liberatoaguilar** [Automattic/simplenote-electron#591]
#### What I expected
Use markdown normally.

#### What happened instead
All markdown features work except headers.

#### OS version
El Capitan

#### Screenshot / Video
![screen shot 2017-07-19 at 11 14 31 pm](https://user-images.githubusercontent.com/30308771/28401580-0ee0fa60-6cd8-11e7-9203-cd40a0e0d038.png)

**Comment by dmsnell** [comment]
Thanks for the report @liberatoaguilar!

Markdown has some funny rules around headers and the standard implementation requires a space after the `#`s and before the content. Can you try adding a space and seeing if it works?

This is confusing with Markdown because different parsers handle it differently, but we hope to try and implement the spec as much as we can. http://spec.commonmark.org/0.27/#atx-headings

**Comment by drw158** [comment]
Also http://commonmark.org requires a space and its the closest thing we have to a standard format.

**Comment by liberatoaguilar** [comment]
I added the space and now it works fine! Thank you very much.
