### ISSUE TITLE
Display date/time of creation and/or last modification in note list

### ISSUE THREAD

**Issue by Topy44** [Automattic/simplenote-electron#599]
It would be useful to see the date and time of note creation and/or the last time it was modified in the note list. This could possibly be part of the "Expanded" view, or a new option entirely.

**Comment by natanielcz** [comment]
I took care of this one. If I should change something drop me a line.

**Comment by thesacredpath** [comment]
I see this is still open. Is it still being considered?

**Comment by iamgabrielma** [comment]
Requested on 1869427-zen

**Comment by iamgabrielma** [comment]
Requested on 1942434-zen

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!

**Comment by cbcaron15** [comment]
is this feature no longer being considered? I can't seem to find the page for this feature request

**Comment by dmsnell** [comment]
@cbcaron15 our feature list is currently private. we consider all feature requests that people make though we don't prioritize them the same way everyone else does (which of course would be impossible because what's a top priority to someone contradicts what someone else consider a top priority).

You can follow the repository or our release notes to discover which features we're working on and put into the app.
