### ISSUE TITLE
Tab width inconsistent across platforms

### ISSUE THREAD

**Issue by Topy44** [Automattic/simplenote-electron#619]
Probably due to different fonts, font size or font rendering, tab width is inconsistent across different platforms. Text aligned properly using tabs in Windows will be misaligned in Linux and Android, and vice versa.
For example, under windows it might look like this:
```
This is quite a long text			aligned
Very short					aligned
This is shorter					aligned
```
And might turn into something like this in Linux:
```
This is quite a long text		aligned
Very short						aligned
This is shorter					aligned
```

I regularly use tabs to format plain text into simple tables, therefore this is quite important to me. A possible fix which would be a nice feature to have anyway would be to make the font and size used configurable. It also allows to choose a monospace font, which some prefer and implicitly fixed the issue.

**Comment by PhiLhoSoft** [comment]
I too use tabs in plain text files to make pseudo-tables, so I find this remark useful, although it would be nice to be able to have some kind of metadata associated to a note to specify tab width (eg. 50 spaces).

In good text editors (eg. Scintilla-based, like SciTE, Notepad++), it works with variable-width fonts because it computes the width of the tab based on the width of the space for the current font, then place all items after tabs at fixed horizontal position to a multiple of this width.

Ideally, the metadata would specify several tab-stops, eg. at 10, 50, 150

Alternatively, a real support of Markdown tables could be nice too...

**Comment by dmsnell** [comment]
Just a quick note that the upcoming `1.1.0` release is going to support Markdown tables :smile:

**Comment by dankind** [comment]
Also noticed going from iOS / OS X to android with tab-indented lists.
eg.


List of items added by iOS/OS X
<tab>- one
<tab>- simplenote automatically creates new tabbed dash with newline

(Same list of items opened on android appears correctly BUT!)
List of items added by iOS/OS X
<tab>- one
<tab>- simplenote automatically creates new tabbed dash with newline
<space>- android seems to forego the previous tab-width and insert a space instead

**Comment by belcherj** [comment]
Closing as we have markdown tables. Additionally tabbing looks more consistent than it was when the issue was opened.
