### ISSUE TITLE
"Download .zip" functionality now working properly for certain system/browsers

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-electron#644]
This comes from an user report here: 729389-zen and was replicated by Linux users on Slack ([ #](https://a8c.slack.com/archives/C2FKVGAD6/p1507709509000019) )

#### Steps to reproduce
1. Go to app.simplenote.com
2. Login
3. Click on Download .zip

#### What I expected

That downloads a .zip file

#### What happened instead

Gets stuck on "loading" or "get the loading spinner for a bit an then a red `Server trouble. (Will retry.)` error"

#### OS version

Linux mint + Chrome
Linux Ubuntu + Chrome
Linux Kubuntu + Chrome

**Comment by dmsnell** [comment]
Is it a large account? I'm pretty sure there are some existing bugs in that download, but most of the times I've seen customers have trouble it's been with large accounts and the server timing out.

In the  meantime, (and we need a better place to report problems with app.simplenote.com since this is the repo for the Electron app), they might try using the Electron app which has its own local export functionality and the export it produces will even give them more data about their notes than the website will.

**Comment by iamgabrielma** [comment]
> Is it a large account?

Not really, around 20-30 notes

> (and we need a better place to report problems with app.simplenote.com since this is the repo for the Electron app). 

Definitely, at the moment we have 11 repos for Simplenote but I was not quite sure were to post the web-related issue, I guessed the `javascript` one would make more sense for this but ¯\_(ツ)_/¯  :D

> they might try using the Electron app which has its own local export functionality and the export it produces will even give them more data about their notes than the website will.

Thanks for the tip, will reach out to the user :)

**Comment by rizomer** [comment]
The Simple Note's Electron app seems to work perfectly even to export/download notes for large account (971kb compressed). Thanks!
