### ISSUE TITLE
Markdown (preview) mode lists problem

### ISSUE THREAD

**Issue by djordjeandrejevic** [Automattic/simplenote-electron#676]
Hi,

I've faced strange behavior while creating a lists in Simplenote 1.1.0. Wasn't sure if that's expected behavior for the markdown, but I tested it later in online markdown tools and they didn't act the same as Simplenote.

#### Steps to reproduce

1. Create a new note and paste the following text (make sure to have markdown for that note enabled):

```
# Test

- test 1
- test 2
- test 3
- 
```

2. Switch from Edit to Preview mode.

#### What I expected

I expected consistently styled list without the bold parts.

#### What happened instead

Last list item turned into bold (maybe even heading?) and the last `-` character disappeared.

![screenshot_289](https://user-images.githubusercontent.com/8862464/33370895-3df4ce74-d4f9-11e7-8cd7-17753866fce7.png)

#### OS version
Ubuntu 16.10

**Comment by dokker** [comment]
Hi,
Maybe this is connected to this issue:

__Markdown:__
```
# test
- __List item:__ This is some text with __strong__ in it
```

__Result:__
![screenshot_2018-02-16_13-27-07](https://user-images.githubusercontent.com/607583/36307631-4f85be16-131d-11e8-8963-d29fe0464bc9.png)

**Comment by tuckerrc** [comment]
I believe it was rendered as a heading.  The single ``-`` is causing it to be rendered as a Heading 2.

```
## Heading 2
```
or 
```markdown
Heading 2
-------------
```
Both render as 

## Heading 2

A possible fix would be to catch a single ``-`` or ``*`` and render a blank bulleted line instead of the heading

**Comment by pauljacobson** [comment]
There is a related issue with how Markdown lists are rendered in the Electron app. Lists that don't include a line space between the text immediately before the bullet points, and the bullet points themselves, are still rendered as formatted lists.

For example, this list shouldn't render correctly because there is no line space before the bullet points:

![](http://cld.wthms.co/njHwa1+)

Instead, it does:

![](http://cld.wthms.co/hiRIjI+)

**Comment by djordjeandrejevic** [comment]
One more issue regarding markdown **numbered** lists.

Paste the following in the note and switch to markdown preview:

```
1. One
2. Two
3. Three

some_text some_text

4. Four
```

Preview mode doesn't continue numbering. Instead it starts from beginning:
![screenshot_480](https://user-images.githubusercontent.com/8862464/43260937-2f559274-90db-11e8-8914-a030653acc4f.png)

Ubuntu 16.10  / Simplenote 1.1.6

**Comment by mfcarneiro** [comment]
I'm using  on Manjaro.

The list note are still showing the markdown, not updating when the preview is off.

![markdown off]()

**Comment by mfcarneiro** [comment]
I'm using on Manjaro here.

The list note are still showing the markdown, not updating when the preview is off:

![](https://user-images.githubusercontent.com/13247083/45151007-8b521c80-b1a3-11e8-9057-b7a1bdd340c6.png)





Manjaro 17.1.12 / Simplenote 1.1.7

**Comment by robertpba** [comment]
The numbering issue reported by djordjeandrejevic affects me too and has caused me to use bullets instead of numbers to avoid this.

It happens without fail when I have some preformatted text within the list like this:

`1. A point`
`2. Another point`
` ``` `
`Some code`
`Some more code`
` ``` `
`3. A third point`

Try it in Simplenote 1.1.7 on Ubuntu 18.04 and the last item renders with a number 1.

**Comment by MrModest** [comment]
![screenshot_simplenote_20181017-175657](https://user-images.githubusercontent.com/13031058/47095515-1cea8a80-d236-11e8-8b64-22defb05d7c9.png)
![screenshot_simplenote_20181017-175706](https://user-images.githubusercontent.com/13031058/47095530-23790200-d236-11e8-8601-423ab91cb164.png)
Checkbox list showing incorrectly
Android 8.1
In Kde Neon works
