### ISSUE TITLE
"Sync Now" button.

### ISSUE THREAD

**Issue by eir87O** [Automattic/simplenote-electron#723]
My Internet connection is very unstable right now and that's giving me some headaches with the syncing. I've read you guys have added a "Warn the user if their notes have or haven't been synced." but it's no use if I have no other option than to Logout and lose my un-synced notes anyway.. This could be easily fixed if there was a Sync Now button that logs last sync time and syncs your notes when it's pressed.

Label this as an feature request, I don't know how to do it myself.

**Comment by dmsnell** [comment]
Thanks for the report @eir87O.

Your notes _should_ be safe when working on an unstable internet connection. As long as Simplenote is open it should be trying its best to synchronize your content. There's no "Sync Now" button because whenever that button _could_ appear the app is already doing everything it can to sync.

We recently added the warning because in some cases people were closing Simplenote after making changes and assuming they were already synchronized when in reality they weren't; the dialog gives people a choice to wait a few extra seconds to let the app finish its work and make the notes available on another device or alternatively to rush out in a hurry.

Should you have concerns about data loss with your notes we'd love to hear about which circumstances were present when you lost notes or note content. Further, we always have the option to export a full backup of all our notes from **File** > **Export Notes**.

For now I'm going to close this issue because we don't have plans to add a sync button for the reasons I gave above. If you think there's reason to add to this though please feel free to add more comments or reopen the issue 😄
