### ISSUE TITLE
HTML tags in Browser not working?

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-electron#725]
I've just tried messing with HTML tags in the desktop version and it works just fine, after I was done I published it and the HTML tags didn't go away in the browser URL like Markdown does.

#### Steps to reproduce
1. Type `<center>Lorem Ipsum</center>` in desktop version and preview it.
2. Try previewing it on browser or published URL.

#### What I expected
Nicely centered-text in published URL.

#### What happened instead
Default left-aligned text with HTML tags around it.

#### Screenshots

![1](https://i.cubeupload.com/Uw394k.png)
![2](http://i.cubeupload.com/53L4zX.png)
![3](http://i.cubeupload.com/CukxgR.png)

**Comment by dmsnell** [comment]
@eir87O thanks for the report. currently `<center>` isn't a tag passed through sanitization which is why it's not working as you expect on the published note. we need to do some investigation before we are able to resolve this though…

@roundhill can you confirm what the server markdown sanitization does with tags it doesn't allow? does it pass them as text or does it strip the tags out and replace them with their inner text?

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
