### ISSUE TITLE
Bold And Italic Markdown With * And _

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/simplenote-electron#768]
When you try to add markdown to a note to make a word/phrase either bold or italic with * or _ both work. 

For example, when I want to make a word italic, I can use either:

`*dog* or _dog_ and both will make the word italic`

Or if I use:

`
**dog** or __dog__`

They both will make that word bold. 

#### What I expected

The symbols "*' and "_" to be responsible for different functions in the markdown. 

#### What happened instead

Both "*" and "_" are doing the same function. 

#### OS version

I have tested on Simplenote app on Mac Hight Sierra Version 10.13.4, Simplenote version 1.3.3. Also have tested on Android, Simplenote version 1.6.0

**Comment by katinthehatsite** [comment]
I thought the issue was confusing, but I will close it since it seems that it is common in markdown to use two options for the same function.

**Comment by dmsnell** [comment]
Thanks @katinthehatsite for creating the issue and for closing it. There are some applications out there (like Slack) which use `*` and `_` for different uses but that at least for me always ends up confusing me because Markdown is pretty clear on its use for bold and italics and they are almost universally consistent otherwise.

We won't make this change therefore as you probably guessed because it would mess up some pretty fundamental expectations for people who write in Markdown. That's an easy frustration though! I wish they behaved the way you describe here with `*` as bold and `_` as italics :smile;
