### ISSUE TITLE
Improve color contrast

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-electron#795]
When in dark mode, the text contrast makes the text almost unreadable.

#### OS version
Windows 10; Simplenote 1.1.6

Reported at #1351437-zen

**Comment by mirka** [comment]
Some improvements we should make:

- Light theme
  - Change the `$blue` from #4895D9 to #287AC3
  - Change `$gray` from #899199 to #6F7780
- Dark theme
  - Change the background from #2D3034 to #282A2E
- Toggle switches: Add cues to that don't rely on color (currently hard to differentiate with red–green color blindness)

**Comment by codebykat** [comment]
There were lots of color updates in https://github.com/Automattic/simplenote-electron/pull/1565 which have hopefully addressed the worst of the contrast concerns, particularly in dark mode. I think it's on the radar to do a more comprehensive contrast audit, but for now I'm closing this issue since it's been almost a year since the last report and quite a bit has changed. Please do re-open if there are specific problem areas still.
