### ISSUE TITLE
Loading a note is slow with many notes in account

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#85]
Load up the `test500@test.com` account, and let it finish indexing. Click on notes in the list, and notice that it takes the detail view a half-second or so to load.

**Comment by dmsnell** [comment]
I'm going to close this issue. It's not because it's not important but rather because we're both very aware of the performance issue _and_ it's a very difficult task to improve upon.

Although the reasons for the performance impact have changed (and it's probably better now than it was when this issue opened) they still remain. The biggest performance bottleneck right now is on very long notes and the time is spent initializing the `draft-js` editor.

Related: #501
