### ISSUE TITLE
Note: Title of the note

### ISSUE THREAD

**Issue by rakhi2104** [Automattic/simplenote-electron#913]
#### Steps to reproduce
1. Separate title field for each note

#### What I expected
There is a title field for each note. 

#### What happened instead
Typing in the note-editor makes first line title, without any confirmation from the user.

#### OS version
- Ubuntu 18.04
- Windows 10

**Comment by mirka** [comment]
I believe this is intentional, so people who don't care about titles don't have to think about it.

For example, Apple Notes (another simple note-taking app) works this way, while Evernote (a more feature-rich app) has a dedicated title field. The downside of a dedicated title field is that users who just want to quickly jot down stuff get a bunch of notes with a title that says "Untitled".

I'm open to design enhancement suggestions in terms of usability though. For instance, one could say that the first line of a note in the editor should not automatically have a larger font-size.
