### ISSUE TITLE
Ability to change the language used for the Spell Check feature

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-electron#949]
Reported originally on 1511012-zen . 

This user has the system settings in Spanish, but uses Simplenote in English. What happens is that the new spell check feature defaults to check the notes using Spanish instead of English.

> I was really excited when I saw on the release notes of 1.21 that you have added spellcheck. The thing is, my Windows (7) system is in Spanish and I usually write in Simplenote in English. I guess it's pulling the language settings from my system because it's correcting everything in Spanish.

> Is there an option to change this? Or would you consider adding a language toggle for future versions?

**Comment by melsophos** [comment]
I agree with this feature proposal. Even more, it would be useful to choose a default language for the full app, and then be able to modify case by case (I tend to write notes in both French and English, sometimes also German, etc.).

**Comment by PhiLhoSoft** [comment]
I was about to create this issue... Glad it is already done.

As said above, we need a global setting to choose the language (and probably to load dictionaries), that would set the default language for new notes.
And we need note metadata (like the "markdown" one), to disable (or enable) spellchecking, and to choose a language.
Like melsophos, I write notes in French and others in English, so I would appreciate to be able to choose case per case.
A quick win here is the capability to disable spellchecking per note: no dictionary management needed yet, and no red squiggly lines in non-default languages.

I hope it is possible to add metadata to notes. Otherwise, perhaps we can imagine a setting where the presence of a given tag (defined by user) will trigger the activation of a given dictionary (or complete deactivation of spellchecking).

**Comment by mirka** [comment]
As a multilingual user myself, I'm annoyed by apps that trap you into a single global language (which nowadays is often the OS language!).

I think both a default language setting and per-note setting are technically feasible, so the problem is mostly a design one (= where to put the settings so we don't complicate things).

I guess we could put the global language setting as a submenu of `Edit ▸ Check Spelling`, where the options would be like:

```
Off
——
Auto
Language 1
Language 2
Etc.
```

For per-note settings, @PhiLhoSoft 's idea to use tags is interesting. Maybe it could be like a hidden, advanced feature, where the syntax (e.g. `spell:en-us`) is documented on the help page.

By the way, our spell checker is supposedly capable of [auto-detection](https://github.com/electron-userland/electron-spellchecker#language-auto-detection). But I think we might be overriding that by explicitly passing the `navigator.language`. Could some of you try [commenting out that line](https://github.com/Automattic/simplenote-electron/blob/master/desktop/context-menu/index.js#L13) and see if the auto-detection seems usable?

**Comment by melsophos** [comment]
> For per-note settings, @PhiLhoSoft 's idea to use tags is interesting. Maybe it could be like a hidden, advanced feature, where the syntax (e.g. `spell:en-us`) is documented on the help page.

In fact, it could go in the note information page (accessed by clicking on the i in a circle in the desktop app), where there is already the "pin-to-top" and "markdown" buttons (if more options come in this page, it might be useful to associate it a shortcut).

**Comment by edequalsawesome** [comment]
User requested spellcheck in additional languages in #1744970-zen as well.

**Comment by edequalsawesome** [comment]
User requested spellcheck in additional languages in #1907360-zen

**Comment by belcherj** [comment]
I’ve added this to our feature requests and we will revisit soon.

**Comment by zyga** [comment]
Bump. I'm using standard notes as a paying customer and on Ubuntu, though the snap, my spell checker follows system language. Ideally I would be able to switch to English for my writing without round-trip through an external editor _or_ without changing my system language.
